### ISSUE TITLE
Key binds to adjust VR kneeboard position

### ISSUE THREAD

**Issue by BG168** [OpenKneeboard/OpenKneeboard#105]
Feature request:  Due to cockpit layout and default head position differences in each aircraft, it would be nice to have key binds to make adjustments to the kneeboard position in 3 axes:
- vertical distance
- left to right position
- forward position

**Comment by franukis** [comment]
+1 This would be absolutely great

**Comment by fredemmott** [comment]
FWIW, I'm hoping to think of a better way to do this than keybinds: changing the positions frequently needs a rotation adjustment too, so we're talking about 12 keybinds - even the 6 for just movement is a lot.

I generally find embedding the desktop window into VR to be the best way to set things up

For making different settings per-aircraft more convenient, there's also #63

**Comment by fredemmott** [comment]
Is this still something y'all feel a need for? Especially with the need for 12 bindings to control all 6DOF, it doesn't seem like it's going to be practical.

There's two cases that come to mind:
- stuff isn't quite in the same place each time you play: use a recenter binding instead
- you need different positions for multiple aircraft: use a different profile (new feature in v1.3) for each aircraft, so you don't adjust the position each time

Does the profiles feature in 1.3 remove the need for this, or is there something I'm missing?

**Comment by franukis** [comment]
For me, having the profiles storing the location to erve different aircraft/modules is enough. I agree it would be too many bindings,  and recentering works fine for me to readjust every time I step into the cockpit :)
