### ISSUE TITLE
Huion Intuos 640P won't write in 1.1 beta unless focussed

### ISSUE THREAD

**Issue by jaylw314** [OpenKneeboard/OpenKneeboard#120]
In 1.1 beta, I can't write on the kneeboard unless the app is in focus over DCS.  I've confirmed neither DCS, the SkateZilla Launcher, or the Huion driver are running in administrator.  I tried the most recent Huion drivers released today, as well as rolling back to previous.  When I rolled back OpenKneeboard back to 1.0, it works fine, though.

**Comment by jaylw314** [comment]
After reinstalling 1.1 beta, it worked fine the second time around, so the problem is not reproducible.  If it occurs again, I'll open a new issue.

**Comment by jaylw314** [comment]
The issue pops up randomly, some launches work and some don't.  I sent logs in discord

**Comment by fredemmott** [comment]
From discord logs:

> "[2022-06-23 00:34:30 DCS.exe (14488)] OpenKneeboard-TabletProxy: Main window: DCS.openbeta"

Any idea what this window title is? It should usually be (from your working log):

> "[2022-06-23 00:29:28 DCS.exe (10940)] OpenKneeboard-TabletProxy: Main window: Digital Combat Simulator"

**Comment by fredemmott** [comment]
Closing: from discord thread, this hasn't happened again; also, the code here hasn't changed.
