### ISSUE TITLE
More visible cursor

### ISSUE THREAD

**Issue by jaylw314** [OpenKneeboard/OpenKneeboard#121]
When you pick up the pen and go to the tablet to write, it can be difficult to determine where the pen tip before writing.  The "hovering" cursor is a very small circle that can be difficult to see.  Having an option to make that cursor larger or a different shape (such as a crosshair or bullseye) for better visibility would be helpful to start writing in the desired location.

**Comment by fredemmott** [comment]
The current shape is handy for small writing, but yeah, it's currently a problem sometimes. Going to try a few things - firstly: it's currently just a black unfilled circle, so is particularly bad on dark pages/content/images. Going to try bordering it with a white circle for a start and see how that goes
