### ISSUE TITLE
Auto-Refresh text file changes

### ISSUE THREAD

**Issue by JaymZZZZ** [OpenKneeboard/OpenKneeboard#133]
Currently, when you load a text file, if you edit that file in any way, you have to remove the tab and add it back in again as a text file on order to see the changes. 

Preferred behavior would be to:

1) If the text file has been edited and saved outside of OpenKneeboard, then the text within the tab should be updated to reflect the change
2) If possible, allow for typing/editing of the text file from within OpenKneeboard

**Comment by fredemmott** [comment]
in-app editing: I don't currently plan to support any kind of in-game keyboard input, as it greatly increases the risk of making the game unplayable if something goes wrong. Removed it from here to make it clear what's actually planned - 1 request per issue is best.

**Comment by fredemmott** [comment]
Adding to v1.2: this is done for v1.1 for folder tabs (and the magic DCS tabs), but not for plain text files or PDFs.

While "has something changed on disk?" will be basically the same:
- I don't want to delay/risk stability of v1.1 by splitting out the code from folder tabs
- The use is a bit different: here, it's probably useful to make it try to understand the change a little - for example, if the change is just adding more stuff and you're on the last page, go to the new last page after reloading. This would likely work well with DCS scratchpad

**Comment by JaymZZZZ** [comment]
Understandable. For what it's worth I was referring to being able to edit the text within the App UI but not necessarily within game. For example, if you are flying within a squad or a group, you may have info regarding the current flight (callsign, loadout, comms channels, etc) that you want to quickly be able to reference. The easiest solution from a usability standpoint would be to be able to past that right into text within OpenKneeboard.

That being said, as long as OpenKneeboard can render the text updates, you can just as easily paste the text into the original txt file and save it there.
