### ISSUE TITLE
Back button in settings

### ISSUE THREAD

**Issue by MansM** [OpenKneeboard/OpenKneeboard#139]
On top and maybe as well on the bottom. So you don't have to click on the settings button again to go to the settings menu, which feels counterintuitive

**Comment by fredemmott** [comment]
Thanks for the suggestion; it's already there, no not particularly prominent. It's the standard place for modern windows apps

![image](https://user-images.githubusercontent.com/360927/177005572-3abdee98-8f33-4364-ba68-de0b02abdd1b.png)
