### ISSUE TITLE
Falcon BMS support

### ISSUE THREAD

**Issue by MansM** [OpenKneeboard/OpenKneeboard#140]
Currently opening kneeboard in game crashes Falcon, more info https://discord.com/channels/807359994856996915/807381918265114634/992796504626569307

**Comment by fredemmott** [comment]
From crash dump, the problem is that the ID3D11Device does not have a viewport set; one can probably be inferred, like in D3D11.cpp

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/177009100-74421a40-2697-4291-8ec6-5b91cdce479d.png)
