### ISSUE TITLE
Add real-world clock to header

### ISSUE THREAD

**Issue by fredemmott** [OpenKneeboard/OpenKneeboard#15]
Useful for VR

**Comment by jonasrembratt** [comment]
+1

**Comment by fredemmott** [comment]
Depends on #116  - no space unless some of the new toolbar icons can be moved to popout menus.

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/207228862-ff0313cf-a92c-49f9-85cc-3ce2831b2217.png)

Working for next beta; leaving this open as I need to add an option to turn it off.

**Comment by fredemmott** [comment]
actually not going to add an option unless people want to turn it off, seems pretty harmelss
