### ISSUE TITLE
Aircraft specific kneeboard included in MIZ mission file won't load

### ISSUE THREAD

**Issue by gkleinfe** [OpenKneeboard/OpenKneeboard#162]
Some of the time, I am using Liberation to generate the mission.  Other times, I'm using Briefing Room to do it. Either way, missions with aircraft specific kneeboard build into the MIZ mission file won't load.

I've attached 2 example files.  I'm using the FA-18C_hornet.
"Caucasus - Operation Immediate Independence.miz" is the Briefing Room file
"liberation_nextturn.miz" is the Liberation file

[Caucasus - Operation Immediate Independence.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/9331331/Caucasus.-.Operation.Immediate.Independence.zip)
[liberation_nextturn.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/9331332/liberation_nextturn.zip)

**Comment by fredemmott** [comment]
Can you attach the logs when trying to use either of those? Settings -> Save As in openkneeboard.

**Comment by gkleinfe** [comment]
Here is a log
[OpenKneeboard-1.2.0.699.txt](https://github.com/OpenKneeboard/OpenKneeboard/files/9334442/OpenKneeboard-1.2.0.699.txt)
.

**Comment by fredemmott** [comment]
There's no aircraft detected for these, so this is probably the same as #81
