### ISSUE TITLE
Request: Add option for creating/copying/saving profiles

### ISSUE THREAD

**Issue by dmeador** [OpenKneeboard/OpenKneeboard#179]
Feature request for creating/copying/saving profiles to allow configuring for different kneeboard (accommodating different airframes in the context of aviation) .
Could create a list of profile names, and load/modify/save from the current selected <profile-name>.json file.  This would be greatly useful!

**Comment by fredemmott** [comment]
Thanks for sharing - I'm closing this as it's the same request as #63
