### ISSUE TITLE
Crash with text files

### ISSUE THREAD

**Issue by DArt503** [OpenKneeboard/OpenKneeboard#187]
With 1.2.0, when adding a folder containing 2 text files called:
0000.txt
0001.txt

Openkneeboard crashs, then it cannot be launched (crash at start).

By editing by hand settings.json file and remove the text folder, it opens normally.

I have added the first text file as files (not as folder) and I got the crash also, so it is seems related to the text file support.

Here is the 2 core dumps in the 2 cases :

[OpenKneeboardApp.exe..zip](https://github.com/OpenKneeboard/OpenKneeboard/files/9580937/OpenKneeboardApp.exe.zip)

**Comment by fredemmott** [comment]
Can you share 0000.txt ?

**Comment by fredemmott** [comment]
nm, one of those "how did this work at the time?" things :(

**Comment by fredemmott** [comment]
You can download a new msix with this fix at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/3067216171 , or it will be in v1.2.1

**Comment by DArt503** [comment]
That is working perfectly ! 
Thanks for the support and the good work on this software ! Love the "all in one" folder (pdf + image) feature, very useful.
