### ISSUE TITLE
1.2.0 Fails to Open

### ISSUE THREAD

**Issue by gkleinfe** [OpenKneeboard/OpenKneeboard#188]
I've been running 1.1.4 and got the upgrade message to 1.2.0.  I perform the upgrade.  Upon completion, OpenKneeboard does not open.  When I click on the icon, I briefly (split second) see and hour glass and nothing else happens.

I uninstalled and reinstalled 1.1.4 which works fine.

**Comment by fredemmott** [comment]
- do you have any openkneeboard .dmp files in `Saved Games\OpenKneeboard` or `%LOCALAPPDATA%\CrashDumps` ? If so, could you share the latest?
- does renaming `Saved Games\OpenKneeboard\Settings.json` make it start? If so, could you share the original settings.json?

**Comment by gkleinfe** [comment]
I've attached the crash dump from %LOCALAPPDATA%\CrashDumps.  Then, I renamed the settings Settings.json to Settings.json.old and relaunched.  It worked.  I've attached the dump and settings file in the zip called OriginalCrash.zip

Seconds later, however, it crashed again.  I can't seem to replicate this crash, so I'll keep an eye on it and report it later if it happens again.

Starting with a clean settings file, I started adding my tabs back.  Adding folders with images works fine.  

I use OverlordBot on my server and am in VR.  I had a problem where I couldn't remember the response.  I wrote an app that parses the server logs and generates a text file that it sends to each client.  I point OpenKneeboard to this text files.  In past versions, the kneeboard would update dynamically, so I had a log of my OverlordBot transmissions.

I can't seem to add these files or the containing folder to the tabs.  Here are some possible scenarios.  The file could be empty (0kb) or not exist at all.  That might be what is causing the problem.

This is the tab that seems to cause the fail.

{
      "Settings": {
        "Path": "C:\\Users\\Gary\\Desktop\\Games\\DCS\\OverlordLogs"
      },
      "Title": "OverlordLogs",
      "Type": "Folder"
    }

It contains the text file I attached called AWACS North.txt.

[OriginalCrash.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/9583546/OriginalCrash.zip)
[AWACS North.txt](https://github.com/OpenKneeboard/OpenKneeboard/files/9583643/AWACS.North.txt)

**Comment by fredemmott** [comment]
For the text file, this already is fixed for the next version, probably in the next few days; you can download an early build with this fix with the MSIX link at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/3067216171
