### ISSUE TITLE
Crash on startup if path to SingleFile type invalid

### ISSUE THREAD

**Issue by BlackBeltMike** [OpenKneeboard/OpenKneeboard#190]
Hi Fred,

Reporting a crash on startup if the path to the .png file below does not exist (such as if I rename the Sectors folder below via File Explorer).  The crash does not occur if path to type Folder is invalid.

      "Settings": {
        "Path": "D:\\MSFS\\Charts\\Sectors\\egpxsectors.png"
      },
      "Title": "egpxsectors",
      "Type": "SingleFile"
    },

**Comment by fredemmott** [comment]
Thanks; also crashes if the file is deleted while OpenKneeboard is running
