### ISSUE TITLE
Add ability to reset tabs to original state (especially radio log)

### ISSUE THREAD

**Issue by iojeda11** [OpenKneeboard/OpenKneeboard#195]
Please add binding to reset (clear out) Radio log tab.

**Comment by fredemmott** [comment]
Relabelled: I won't be adding a dedicated binding for this, but it's should be practical once there's a more flexible per-tab menu system (also things like 'clear notes' per tab/page)

**Comment by fredemmott** [comment]
blocked on #116

**Comment by fredemmott** [comment]
@iojeda11 when do you want to do this? While resetting-to-default should be added for *every* tab, would adding an option to automatically clear the radio tab when mission is started/restarted/changed also fix this for you?

**Comment by iojeda11** [comment]
@fredemmott 
The idea behind adding a binding for it was to allow do it on demand, when needed (certainly during mission start, perhaps when changing slots/planes during a mission) ... Perhaps the same binding could reset to original the tab with the focus? 

Doing the reset automatically at mission start, will definitely work. Specially with the radio log... It clutters real quick :)

**Comment by fredemmott** [comment]
Added this for the next version:

![image](https://user-images.githubusercontent.com/360927/192302105-2831e744-0d6a-453d-9d8a-8a226c54ab60.png)

Leaving open for general case, which is blocked on #116

**Comment by iojeda11** [comment]
Excellent! Thank you!
