### ISSUE TITLE
Support for OpenTablet Driver

### ISSUE THREAD

**Issue by kknuut** [OpenKneeboard/OpenKneeboard#199]
I have Huion H640P, and G2 VR on OpenXR, playing DCS.  Huion driver seems to often drop tablet and does not recognize it, It takes more time to get it working than to play... Reason for drops being unclear. But this lead me to seach for alternative and found OpenTabletDriver project which supports many tablets.

https://github.com/OpenTabletDriver/OpenTabletDriver

Unfortunately that Driver does not support WinTab interface, and by searching their discussions they are not planning to add support for that. It seems that Wintab is quite problematic interface.

OpenTabletDriver should support Windows Ink interface (at least with separate plugin + driver). Have not tested yet.
And they have their own driver, but I'm not sure how stable interface that has. 

Nuget package:
https://www.nuget.org/packages/OpenTabletDriver

Would it be possible to support OpenTabletDriver or Ink with this great kneeboard, which already made me purchase the tab!

**Comment by fredemmott** [comment]
Sorry, I'm closing this as it's not something I'll be working on. That said:

1. if [OpenTabletDriver is extended to support an alternative interface and background mode](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/1230#issuecomment-1059217948) or a plugin doing that is written and maintained by someone else, I'd be open to adding support in OpenKneeboard
2. I'd also be open to a pull request adding support for windows ink similarly to wintab support, by modifying the game process

Requirements would be:
- good performance, both in terms of resource usage and 'feel' when drawing
- confidence in the security aspects of the IPC, e.g. doesn't seem likely to give others on the network the ability to snoop on or control mouse/tablet events
- no dependency on C# or the .net framework in OpenKneeboard itself, or in DLLs that are injected into the game process (e.g. that nuget package can't be used)

I wouldn't take a PR adding direct support for OpenTabletDriver in a similar way to wintab by modifying the game process: this would be largely equivalent to (1) but more complicated and brittle

**Comment by fredemmott** [comment]
Re-opening; there are issues with the Huion driver that are unlikely to be fixed, and this would also enable support for other brands.

This would require writing the plugin to support a non-windows-ink interface. Currently leaning towards zeromq, but not really set on it.

**Comment by kknuut** [comment]
Update from my part. 

Got it working reliably after changing to USB port that is always connected to PC. I had it initially behind USB switch for two pc's.

**Comment by fredemmott** [comment]
Some cleanup needed, however, got basics of OTD -> separate C++ process working

![image](https://user-images.githubusercontent.com/360927/209446405-55f7c3e3-9f72-40f0-870e-3308fc2ab6a2.png)

**Comment by fredemmott** [comment]
Plugin here: https://github.com/OpenKneeboard/OTD-IPC

OpenKneeboard support still a work in progress
