### ISSUE TITLE
Add DCS mission briefing as kneeboard page/tab

### ISSUE THREAD

**Issue by niclas-jansen** [OpenKneeboard/OpenKneeboard#20]

**Comment by fredemmott** [comment]
.miz is a zip file; main `mission` file there is mostly a cross-reference to other stuff in l10n/DEFAULT/dictionary, which in turn can refer to images in the same location

Will likely require embedding LUA to do reliably

Unclear how DCS decides which frequencies to list in briefing.

**Comment by fredemmott** [comment]
- [ ] #83 - 'collection of pages' and 'tab' need to be distinct concepts internally
- [ ] 'image page' needs to be decoupled from 'folder of images'
- [ ] actually load the LUA dictionaries from the .miz

**Comment by fredemmott** [comment]
Calling this done, and should be in 1.2

## Added

- mission title and start time
- involved countries
- "Situation"
- "Objective" (varies by coalition)
- Temperature, QNH, Cloud cover, nav wind
- briefing images (varies by coalition)

## Missing

- "my task", info on own and allied flights, known threats
- armament carried
- turbulence
- "Take Off and Departure" - frequencies and QFE

Happy to add missing data if there's pointers on how to cross-reference the .miz lua files or other DCS lua data files with the information available via the gui hooks (LoGeSelfData and friends)
