### ISSUE TITLE
Audio Switcher Streamdeck plugin change default and communications with one action.

### ISSUE THREAD

**Issue by LiveWithMadness** [OpenKneeboard/OpenKneeboard#204]
Hi,

I've been struggling to use this Streamdeck plugin (Audio Switcher) because it doesn't allow the Default Audio device at the same time that it changes the communications device. This is quite annoying because, e.g., you're playing games with friends over Discord and want to switch your whole audio to be outputted through headset, instead of speakers. You should use 2 buttons to do that as you need to change the default device (for it to affect the game) and then the communications device (for it to affect Discord).

If it makes things easier, before using this plugin, I used an executable (AudioSwitcher.exe) that allowed me to shortcut these actions on specific keybindings. Besides, this program offered an option to make it change both (default and communications devices) outputs with one shortcut. I'll add some screenshots at the end of this post in case I'm not making myself clear.

Could this be added to the Streamdeck plugin?

Thank you in advance.

![audioswitcher-settings](https://user-images.githubusercontent.com/99535862/196253566-f5d9c581-0ebb-4d24-9f7e-498e2f773a76.png)

**Comment by fredemmott** [comment]
Not related to OpenKneeboard; do not open other streamdeck-related issues here. That said, you want to use Elgato's built-in multi-action switch functionality.
