### ISSUE TITLE
Kneeboard anchored to a fixed location rather than to Application

### ISSUE THREAD

**Issue by radlouni** [OpenKneeboard/OpenKneeboard#211]
I use openkneeboard with DCS in VR. I position the kneeboard in such a way that it is on my knee, but when i have to recenter the VR view the position of the kneeboard relative to my knee changes since the kneeboard is anchored to a fixed location relative to the headset rather than to a fixed location relative to DCS. so for example if the kneeboard is on my knee, and I move my head right and recenter the VR view, the kneeboard position shifts to the left relative to my knee. This is a pain continuously having to repsotion the kneeboard every time the VR center view changes.

**Comment by fredemmott** [comment]
The games don’t provide a way to anchor to their center. the best way to address this is to bind the same combination to recenter openkneeboard and the game
