### ISSUE TITLE
PDF files cannot be overwritten when OpenKneeboard is running

### ISSUE THREAD

**Issue by BlackBeltMike** [OpenKneeboard/OpenKneeboard#214]
Use-case is exporting from SimBrief into the tab folder, then start openkneeboard.  Now if there's a change of plan, the pdf cannot be deleted or overwritten without restarting OpenKneeboard.  This is particularly unfortunate as notes written via a tablet will be lost with the restart. 
Would be good if the PDF file handle is released and reopened if there's a content change.

**Comment by fredemmott** [comment]
Microsoft’s PDF renderer locks it - going to workaround by copying it first, so need #212 first
