### ISSUE TITLE
Add list-of-tabs in game

### ISSUE THREAD

**Issue by mjfrisby** [OpenKneeboard/OpenKneeboard#218]
It would be nice to have a table of contents tab that gets dynamically updated with a numbered list of the current tabs in the kneeboard.

I am controlling OpenKneeboard via VoiceAttack and vJoy (via SPAD.nExt script panel).  As it stands, in order to access a tab such as "mission brief", I have to place that tab in a specific spot in the kneeboard so that I can navigate to it using a combination of "tab forward" and "tab backwards" button presses.

If there was a Table of Contents tab, I could pull that up and then just "go to tab 5", which would then result in 5 "forward" button presses via the SPAD script.

**Comment by fredemmott** [comment]
It's not yet released, but check out https://github.com/OpenKneeboard/OpenKneeboard/blob/d8f0f5ca1e9550f52cf1376837dac4d35432ff3b/docs/remote-controls.md for an alternative approach for voice attack in future versions

**Comment by mjfrisby** [comment]
Aha.. yeah, that will be a much more elegant solution than how I am currently doing it.  I did actually consider submitting that idea, as I use that method in mbuccia's OpenXR Toolkit quite a lot.  

Would also be cool if there was a native OpenKneeboard plugin for voiceattack too..

**Comment by fredemmott** [comment]
The renderer-neutral part is done, but I've not yet implemented an in-game renderer for these. That's #231

![image](https://user-images.githubusercontent.com/360927/209681195-88579125-cc4b-4e48-8f81-a03c96a7d334.png)

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/210095847-ddc139b3-d23e-44bf-8030-f862c8c91123.png)
