### ISSUE TITLE
Crash when switching profiles 1.3-beta3 if tablet driver doesn't initialize

### ISSUE THREAD

**Issue by NoSie** [OpenKneeboard/OpenKneeboard#220]
Hi, whenever I switch to a different profile openkneeboard crashes. (Also happend in 1.3-beta2 for me)
Here is the Event Viewer crash report:

Name der fehlerhaften Anwendung: OpenKneeboardApp.exe, Version: 1.3.0.898, Zeitstempel: 0x638d059a
Name des fehlerhaften Moduls: OpenKneeboardApp.exe, Version: 1.3.0.898, Zeitstempel: 0x638d059a
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000010f13f
ID des fehlerhaften Prozesses: 0x44ec
Startzeit der fehlerhaften Anwendung: 0x01d908938b48c326
Pfad der fehlerhaften Anwendung: C:\Program Files\OpenKneeboard\bin\OpenKneeboardApp.exe
Pfad des fehlerhaften Moduls: C:\Program Files\OpenKneeboard\bin\OpenKneeboardApp.exe
Berichtskennung: a22a9546-502a-444e-8963-bbc923c4b27b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by fredemmott** [comment]
Thanks, the dump was extremely useful :)

The crash happens if the wacom/huion driver doesn't initialize.

This definitely happens if there is no wacom/huion driver installed - however, at least for wacom, it doesn't happen if you just unplug the tablet.

**Comment by fredemmott** [comment]
This will be fixed in v1.3-beta4, or - probably - an msi at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/3621704111 in 20-40 minutes

**Comment by NoSie** [comment]
That was quick! Thanks! :)
