### ISSUE TITLE
Feature Request: SET_NEXT_PROFILE / SET_PREVIOUS_PROFILE remote control

### ISSUE THREAD

**Issue by NoSie** [OpenKneeboard/OpenKneeboard#221]
I use different profiles to hold the different document collections for each aircraft and some for general docs. Would be cool if those could be stepped through with with button presses while in VR.

**Comment by fredemmott** [comment]
Already done in master for the next beta :)

**Comment by fredemmott** [comment]
Hmm, actually not next/previous, just set by id/name, so button presses won’t work well

**Comment by fredemmott** [comment]
You might want to add `"LoopProfiles": true` to `Saved Games\OpenKneeboard\profiles.json` - it works similarly to the 'loop tabs' and 'loop pages' options:

**Comment by NoSie** [comment]
Great stuff! Thanks you! :)

**Comment by fredemmott** [comment]
Added another option here

![image](https://user-images.githubusercontent.com/360927/210120313-fcb46364-b7cd-4fb7-b9bb-49a091ac9a2f.png)
