### ISSUE TITLE
profiles: Two kneeboard setting does not stick

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#225]
I did make a new profile, enabled two kneeboards in advanced and closed the App. 

After re-starting the app, the two kneeboard setting does not stick and reverts to single.

**Comment by fredemmott** [comment]
Which version?

**Comment by fredemmott** [comment]
I can't reproduce this with beta4 - though keep in mind that the dual kneeboard setting is part of the profile.

There is a small UI bug: the 'advanced setting' page isn't updating what is shown for this setting when switching profiles

**Comment by LtJaeger** [comment]
Newest beta. Ran into more problems last night which I can not describe in the moment. Will check from start and report back.

**Comment by LtJaeger** [comment]
OK, issue can be closed. A re-install fixed that behaviour. Sorry
