### ISSUE TITLE
Add support for custom OpenKneeboard tabs (not DCS tabs) written in something friendlier than C++

### ISSUE THREAD

**Issue by fredemmott** [OpenKneeboard/OpenKneeboard#240]

**Comment by fredemmott** [comment]
It's really discouraging that the C API documentation was removed (https://github.com/facebook/yoga/issues/721) , but [Yoga](https://github.com/facebook/yoga) may be a useful tool for laying these out.

**Comment by fredemmott** [comment]
Now that there's a *limited* browser built-in, it could make more sense to use HTML+Javascript for these instead.

**Comment by fredemmott** [comment]
APIs should include:
- [ ] desired resolution (already sort-of supported via simhub-specific API)
- [ ] 'page-based' vs scroll-based option, integrating with standard OKB page bindings. This should trigger JS events for 'next page'/'previous page', JS should toggle element visibility or replacement instead of sending pageup/pagedown keypresses, as these can be 'weird'
- [ ] GUID generation, for page IDs (page IDs are used instead of numbers so that if there are 3 pages and page 2 is deleted, it's easy to track actions such as doodles that were done on page 3 as now being on page 2; this would also tie into persistence)
- [ ] bool for cursor passthrough vs OpenKneeboard's standard doodles
- [ ] 'reload this page' event
- [ ] set default tab title

**Comment by amadeus** [comment]
I have a side project — https://kneeboard.live where I’ve developed a pretty rich interface for checklists. Would be neat if I could run those as they are in OpenKneeboard.

An example checklist and how it works can be viewed here: https://kneeboard.live/amadeus/f8e32003-62f6-491b-b108-16fe8909a552

**Comment by fredemmott** [comment]
Resolution/aspect ratio can now be controlled with:

```Javascript
if (window.OpenKneeboard?.SetPreferredPixelSize) {
  window.OpenKneeboard.SetPreferredPixelSize(width, height);
}
```

Everything else is still 'maybe in some future version'.

**Comment by fredemmott** [comment]
how about keeping `SetPreferredPixelSize` for 'act like a browser, but there's a good form factor' stuff, where standard interaction, mouse emulation, etc is wanted. For more detailed stuff:

```
OpenKneeboard.Initialize({
  PreferredPixelSize: { width: 1024, height: 768 },
  DefaultTabTitle: "Example",
  Pages: {
    [
      {
        guid: "use crypto.randomUUID()",
        ?name: "name for page, or omit",
      },
    ],
  },
  Capabilities: {
    // no mouse interaction, standard OKB per-page drawing canvas wanted
    "DoodlesOnly",
    // Supports 'clear notes' -> 'all pages'. Implied by 'DoodlesOnly'
    "ClearNotesAllPages",
    // Supports 'clear notes' -> 'this page'; requires 'ClearNotesAllPages'. Implied by 'DoodlesOnly'
    "ClearNotesThisPage",
  },
  // Handles message received via https://openkneeboard.com/api/ , a.k.a. 'Game Events'
  IPC: [
    'dcs/Aircraft',
    'dcs/Mission',
    'bms/*',
    '*',
  ],
});
OpenKneeboard.addEventListener(
  'ClearNotesThisPage',
  (ev) => { /* ev includes page guid */ });
OpenKneeboard.addEventListener(
  'PageChanged',
  (ev) => { /* ev includes page guid */ });
OpenKneeboard.addEventListener(
  // JS event type contains the pattern, not the actual event name
  'IPC/bms/*',
  (ev) => { /* ev includes full event name and payload */ });
```

There is a complication when switching to page based: when using OpenKneeboard with multiple views, each view should have its' own idea of the current page. To handle this efficiently when both views are visible, that means each view will need its' own browser running it's own instance of the web page, but if you're viewing the same page in both views, you should expect a change in one to affect the other - so, these browsers need to be able to communicate. This would likely be `OpenKneeboard.dispatchSiblingMessage(YOUR_TYPE, YOUR_PAYLOAD)` and `OpenKneeboard.addEventListener('siblingMessage/YOUR_TYPE')`, where a 'sibling' is another browser showing the exact same tab (by tab GUID, not just any tab showing the same URL - the same C++ object instance)

**Comment by fredemmott** [comment]
`PreferredPixelSize` should not be a top-level element as it should be able to vary per page; instead, we should have:

```JSON
Pages: [
  {
    GUID: "a value from crypto.randomUUID()",
    PreferredPixelSize: { width: 1024, height: 768 },
  }
]
```

**Comment by fredemmott** [comment]
Brief example of that new `RawCursorEvents` feature (more details in docs):

![image](https://github.com/user-attachments/assets/6c15a9ed-dbee-4d13-93fd-6955a9e78916)

This is primarily to work around bugs/limitations of cursor injection support in WebView2.

**Comment by fredemmott** [comment]
"Pages-based" is effectively a Single Page Application with:
- a custom API
- if you have multiple views, each 'view' is a separate browser instance. Pages must communicate either via standard methods (e.g. local storage, web sockets), or a simple message-passing system that I'll add.

Not yet ready for even experimental use, but here's what the test html page looks like at the moment with two views:

![image](https://github.com/user-attachments/assets/e85b6ede-734f-43be-a921-d78e1ee0785f)

**Comment by fredemmott** [comment]
Calling this done - essential APIs exist in v1.9 (current github actions builds), and are documented at:

- https://openkneeboard.com/api/web-dashboards.html
- https://openkneeboard.com/api/web-dashboards/page-based-content.html

Further requests/features are best addressed through separate GitHub issues per request/feature; discussion that isn't focused on a particular request is best in `#code-talk` [on Discord](https://go.openkneeboard.com/discord).

No ETA for an actual v1.9+ release - this depends on feedback and unrelated changes/features. If you'd like to try this out, grab a github actions build

**Comment by fredemmott** [comment]
C# and Rust would be possible and give better results, but would require:
- a C API+ABI to be built first
- C#: NativeAOT
- Both: Direct3D interop that accepts raw C pointers. For C#, I think this would mean terrafx
