### ISSUE TITLE
Bug: First page loop does not work

### ISSUE THREAD

**Issue by OR-WS** [OpenKneeboard/OpenKneeboard#246]
In version 1.3, in 2D, even though last page/first page loop is enabled, last page forward loop works but first page backward loop does not.

Last tab/first tab looping works fine.

**Comment by fredemmott** [comment]
I'm not able to reproduce this; are you seeing it on every tab, or just some specific tab?

**Comment by OR-WS** [comment]
> I'm not able to reproduce this; are you seeing it on every tab, or just some specific tab?

Curious. It seems fixed with v1.3.1.

**Comment by fredemmott** [comment]
Closing for now; the changes in v1.3.1 don't seem related, but for now at least, there's no way for me to act on this.
