### ISSUE TITLE
VB6 (32-bit?) borderless window capture

### ISSUE THREAD

**Issue by danoveb** [OpenKneeboard/OpenKneeboard#248]
The captured windows need to have borders, otherwise the app will crash. Also, a possibility to hide the border that this app adds to the window should be nice.

**Comment by fredemmott** [comment]
Can you give an example? I'm not able to reproduce any problem here, e.g. with the borderless DCS mirror window:

![image](https://user-images.githubusercontent.com/360927/213866829-ffbc2fa5-a1a6-400d-bf9e-fdf26be92a59.png)

**Comment by fredemmott** [comment]
>  Also, a possibility to hide the border that this app adds to the window should be nice.

This appears to require windows 11, which I'm unable to build/test with.

**Comment by fredemmott** [comment]
> Also, a possibility to hide the border that this app adds to the window should be nice.

Should be an MSI at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/3974919879 in ~ 45 minutes which *might* remove that yellow border on Windows 11. Or might crash on Windows 11. It at least does nothing on Windows 10 :p

**Comment by danoveb** [comment]
This is the windows I capture:
![image](https://user-images.githubusercontent.com/25252373/213885341-dffa03a1-8b4a-4eb6-ac5a-0bb10887912b.png)
And this is how it looks in the HMD
![image](https://user-images.githubusercontent.com/25252373/213885393-4f98bdc1-a4e8-4f16-9723-bc1a453aa54d.png)
You can see the Grey frame both above and beneath the captured window. 
The window is a VB6(!) applikation. If I make the windows borderless, the OpenKneeboard app crashed/doesn't show the window.

**Comment by fredemmott** [comment]
I'm not able to reproduce this with a classic Win32 `WS_POPUP` window (which does not have a border or `WS_BORDER`):

![image](https://user-images.githubusercontent.com/360927/213888725-d40a9d07-dc39-45d8-acbf-85fc228378cf.png)

Do you have any recent .dmp files in Saved Games\OpenKneeboard or %LOCALAPPDATA%\CrashDumps ? If not, download and run https://github.com/OpenKneeboard/OpenKneeboard/blob/master/docs/enable-full-dumps.reg , then try again + check again

**Comment by fredemmott** [comment]
> the app will crash.

Is this the VB6 app, or the OpenKneeboard app?

**Comment by fredemmott** [comment]
> You can see the Grey frame both above and beneath the captured window.

Ah, I thought you meant the yellow border around the captured window.

I've made the header and footer optional for v1.4.

The header is useful if you have multiple tabs, both for showing which one you're on, and - if you have a wacom/huion/similar drawing tablet, it allows in-game control of the kneeboard.

The footer shows the current real-world time, and if someone writes a plugin, in-game time; e.g. for DCS World where multi-hour games are common (and saving is impossible), it shows:
- real-world local time
- in-game local time
- in-game zulu/UTC time

**Comment by danoveb** [comment]
Great with that option! It's the OpenKneeboard app that crashes. I tried to find som logs. Where is the data directory?

**Comment by danoveb** [comment]
Dump file: https://drive.google.com/file/d/1QA2SQEcbkB1ghiM6kJU70JZ_HLVBe9SC/view?usp=sharing

**Comment by fredemmott** [comment]
> Maybe your app cannot find the window name when it has no border?!

It works fine with borderless 32- and 64-bit C++ applications, or when it can't find the window at all; however, Windows is reporting that capturing your window is unsupported - probably the combination of borderless + VB6.

**Comment by fredemmott** [comment]
v1.4 will probably not crash on this; it won't support it either though, as Windows is reporting it's unsupported.

**Comment by fredemmott** [comment]
>  32 bit yeah. I don't expect support for an old app like that.

All VB6 apps are 32-bit, but most 32-bit apps are supported by OpenKneeboard - they're still surprisingly common, e.g. Discord.

**Comment by danoveb** [comment]
Ok. Did a workaround. After Kneeboard is started and have found the window, I change the BorderStyle in the app.
