### ISSUE TITLE
Microstutter when using non-vr D3D11 kneeboard (e.g. via autodetect)

### ISSUE THREAD

**Issue by matthlsile** [OpenKneeboard/OpenKneeboard#255]
Hi, 

first thanks for this fantastic tool.

I'm using Version 1.3.2 for DCS and Falcon BMS and have an issue with "Auto-detect" Rendering API.
My Headset is a Reverb G2. Intel i9 13900k, 4090, 64 GB, Windows 11.

My issue:
**:: Falcon BMS ::**
"Game Gettings :: Rendering API :: Auto-Detect" introduces stuttering when openkneeboard is shown. No stutters when kneeboard is closed or Rendering API "SteamVR" is selected.

**:: DCS ::** (ED reverted to OpenVR as default at the time i'm writing this)
**OpenVR -> SteamVR**   - fine with "Auto-detect". No performance issues.
**OpenXR (Opencomposite) -> WMR Runtime**   - fine with "Auto-detect". No performance issues.
**OpenXR (native --force_OpenXR ) -> WMR Runtime**   - not tested
**OpenXR (native --force_OpenXR) -> SteamVR Runtime**    - stuttering with "Auto-detect". 

In all problematic cases stuttering is not to be seen when kneeboard is closed or Rendering API "SteamVR" is selected. 
So it's not a big deal since i can select SteamVR to avoid stuttering. But I would have to switch the Rendering API to be able to use it in 2D, then.

Just wanted to let you know my observations. Maybe it's possible to optimize the auto-detect function?

Thank you.

Matthl

**Comment by fredemmott** [comment]
For BMS, can you share the file that this creates after this has happened:

![](https://github.com/OpenKneeboard/OpenKneeboard/raw/master/docs/screenshots/save-logs.png)

> OpenXR (native --force_OpenXR) -> SteamVR Runtime - stuttering with "Auto-detect".

The stuttering here is likely that the autodetect finishes, but in 1.3 and below (fixed for 1.4) it doesn't detect OpenXR, so the non-VR and SteamVR versions are running simultaneously.

This in turn leads to a few possibilities:
- simply having two renderers active at the same time is a problem
- the non-VR renderer is interacting with some other invasive Direct3D software (OpenKneeboard's non-VR renderer is also invasive - there's no other renderer)

For both of these cases, the solution is to disable autodetection.

For BMS, it's likely an interaction with other software; it should detect SteamVR, but it still needs to inject itself into the Direct3D frame loop to figure out what's going on. If anything else is doing that, it can go badly.

Try also stopping *any other* software that interacts with the rendering - this includes things like other overlays (Discord, Rivatuner, MSI afterburner, the Steam overlay) and OBS, XSplit, or any other capture/recording/streaming tools.

**Comment by fredemmott** [comment]
Also remove any modes that replace d3d11.dll or dxgi.dll, e.g. shader mods.

**Comment by matthlsile** [comment]
[OpenKneeboard-v1.3.2.1147-2023-01-29-07-51.txt](https://github.com/OpenKneeboard/OpenKneeboard/files/10529209/OpenKneeboard-v1.3.2.1147-2023-01-29-07-51.txt)

Saved after about 1 minute running Falcon BMS 4.37.1with "Auto-detect" on. No additional interacting software that i'm aware of. The stuttering happens all the time.

**Comment by fredemmott** [comment]
Thanks; the auto-detection is finished at that point, and non-VR support is loaded. Two things here then:
- figuring out why the non-vr support is stuttering
- figuring out why the autodetection doesn't detect steamvr is being used by bms

**Comment by fredemmott** [comment]
> figuring out why the autodetection doesn't detect steamvr is being used by bms

Falcon BMS directly embeds openvr_api inside `Falcon BMS.exe` instead of using `openvr_api.dll`; build-time optimizations in BMS mean that the functions can not be safely located, so autodetect will not be able to identify that steamvr is in use. That part of this is not going to be fixed.
