### ISSUE TITLE
No Index if a Tab (Folder) contains several pdf

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#257]
If I make a TAB - Folder typ, and link it to a windows folder with several PDFs in it, there is no Index. OK handles the pdfs as one big one.
![grafik](https://user-images.githubusercontent.com/103137203/215497850-129bb056-b202-4de0-a3d1-a80e05a2e980.png)
![grafik](https://user-images.githubusercontent.com/103137203/215497955-a64d18ce-529a-4bd0-bb8d-cb2b34a41e52.png)

**Comment by fredemmott** [comment]
I'm not seeing anything with folders here - do the PDFs you're using *have* indices? If so, they're being merged correctly for me.

If they don't, I'm seeing a bug where - unlike for images - OpenKneeboard will currently never autogenerate an index for PDFs without an index, regardless of if there's a folder or not.

**Comment by LtJaeger** [comment]
No Index. I linked the S&A Briefing folder to OK. Like I said, the PDFs are considered as one big one. So if I start at PDF 1, to get to PDF 5, I need to step through all the pages in between.

**Comment by fredemmott** [comment]
Ok, this sounds like the not-folders thing I fixed for v1.4 :)
