### ISSUE TITLE
Capture Mouse Cursor in Window Capture tabs

### ISSUE THREAD

**Issue by EliasFinoli** [OpenKneeboard/OpenKneeboard#259]
I'm using OpenKneeboard for simracing and to capture apps like Discord etc, however actually doing stuff in them is really hard due to there not being a mouse cursor visible in the capture.
Would adding this be feasible?

**Comment by fredemmott** [comment]
Are you trying to use a real mouse, or are you using a graphics tablet in combination with OpenKneeboard?

I *can* add the real mouse cursor, however the mouse only works correctly in windows for the active window, which is almost always the game. If the mouse isn't locked to the active game, clicking on discord etc will make discord the active window; if this would be useful to you, could you explain more about the software you're using and why this would be useful?

If you're using a graphics tablet in combination with openkneeboard, openkneeboard does draw a mouse cursor; is that not showing up, or it it just too subtle?

**Comment by EliasFinoli** [comment]
> Are you trying to use a real mouse, or are you using a graphics tablet in combination with OpenKneeboard?
> 
> I _can_ add the real mouse cursor, however the mouse only works correctly in windows for the active window, which is almost always the game. If the mouse isn't locked to the active game, clicking on discord etc will make discord the active window; if this would be useful to you, could you explain more about the software you're using and why this would be useful?
> 
> If you're using a graphics tablet in combination with openkneeboard, openkneeboard does draw a mouse cursor; is that not showing up, or it it just too subtle?

I'm using a mouse and the game I'm playing is iRacing, which does not require focus to work in VR and doesn't lock the mouse, so while I'm in the pit/loading/spectating it would be nice to be able to interact with the window captures I have (e.g. Discord, Chrome etc).
One thing I often do is start a stream in the voice channel, which is a bit hard to do without seeing the cursor.
This might be a niche request and it not being visible unless the window is actually the active window might make it suboptimal but still better than currently!

I completely understand if you'd be reluctant to add this functionality as it might see very few users :)
