### ISSUE TITLE
Uninstall doesn't remove \Users\user\Saved Games\OpenKneeboard

### ISSUE THREAD

**Issue by slally** [OpenKneeboard/OpenKneeboard#260]
After running uninstall from Add/Remove programs on Windows 10 the \Users\user\Saved Games\OpenKneeboard directory still exists.

![image](https://user-images.githubusercontent.com/5423542/218316910-8dbc6128-af05-4ba5-bea8-a3778482f7f4.png)

(Was trying to sort out a problem I created by adding a directory by uninstalling and reinstalling.  After reinstall my errant directory was still showing up in OpenKneeboard.)

**Comment by fredemmott** [comment]
Sorry, I won’t be changing this; it’s very common for people to try uninstalling and reinstalling, and they don’t expect to have to redo their settings.

**Comment by slally** [comment]
Thanks for looking and explaining.
