### ISSUE TITLE
HUION Inspiroy H430P compatibility

### ISSUE THREAD

**Issue by OldDog68** [OpenKneeboard/OpenKneeboard#261]
as per topic is this model compatible?

**Comment by fredemmott** [comment]
For the fewest problems, I recommend a Wacom Intuos S; the Huion H640P is probably the most popular though.

I don't know of people using this tablet, however it most likely works with Huion's own driver, and is alternatively listed as supported by https://opentabletdriver.net/Tablets - it most likely works.
