### ISSUE TITLE
Coordinate entry functionality

### ISSUE THREAD

**Issue by edmuss79** [OpenKneeboard/OpenKneeboard#275]
As suggested on discord.

Could it be possible to have a page dedicated to coordinate inputs with a self contained numeral pad selectable with the stylus.

Each line would have a coords entry box with a small notes area to the side for a brief hand written description/time etc. if needed.

Possible other functionality could be auto conversion to the different formats. When entering coords you could preselect what format you're entering, fill in the numbers and it will then spit out a line with the different formats.

This could be useful for making notation of flight plan waypoints or a list of targets to hit. Added bonus, if the coords written on the fly (rather than DCS mission generated) and the airframe is lost, the same information is retained on the kneeboard if you choose a new slot.
Also would save me having to decipher my hand writing 😁

**Comment by fredemmott** [comment]
> numeral pad 

Just to note that for MGRS input support, needs to be alphanumeric

**Comment by fredemmott** [comment]
For v1.9+ this can be built by as a plugin by anyone familiar with javascript, similar to https://github.com/OpenKneeboard/Calculator-Plugin
