### ISSUE TITLE
Add setting for starting the app in a minimized state

### ISSUE THREAD

**Issue by Shinjo-B** [OpenKneeboard/OpenKneeboard#281]
Low priority, but thought I would throw this in here. Would love to the ability to start the app minimized.

**Comment by fredemmott** [comment]
This was not really possible when using MSIX (#219 - cc @Rufuz64), but with the move to MSI, probably is: even though the framework doesn't support it, I should now be able to just pull it out of `GetCommandLineW()`

**Comment by fredemmott** [comment]
Done in https://github.com/OpenKneeboard/OpenKneeboard/commit/b2376a0461879fa2430c13e5cc8c69c8335df300 for v1.4 (hopefully), which adds support for this by adding `--minimized` to the shortcut (or arguments in voice attack etc)

This may stop working in a future release, or may cause bugs that mean I have to undo this: according to Microsoft, I **must always** call a Microsoft-provided function, which shows the window, and *may* do other essential things.

For now, it looks like it doesn't actually do anything other than show the window, so I can do that the old fashioned way.
