### ISSUE TITLE
App crashing when trying to change tabs order

### ISSUE THREAD

**Issue by SchmidtDawid** [OpenKneeboard/OpenKneeboard#322]
App crashing when trying to change tabs order

**Comment by fredemmott** [comment]
Dont' run OpenKneeboard as administrator.

This is a microsoft bug that can only be fixed by Microsoft.

https://github.com/OpenKneeboard/OpenKneeboard/issues/249

**Comment by SchmidtDawid** [comment]
Thanks. Yeah it works :)
