### ISSUE TITLE
Graphics glitches in Dirt Rally 2

### ISSUE THREAD

**Issue by Raptyyy** [OpenKneeboard/OpenKneeboard#324]
Using OpenKneeboard in Dirt Rally 2 will cause the games graphics to glitch out and look over exposed, making the game unplayable.
Some example images: 
<img src="https://user-images.githubusercontent.com/29117629/230417259-5de43cc2-043d-4bcc-bad0-7dd7be8bb9a4.png" width="50%" height="50%">
<img src="https://user-images.githubusercontent.com/29117629/230417282-4fbae2e9-1b73-4988-9fa1-bb0ffa1c62a0.jpg" width="50%" height="50%">

Seems to only happen when OpenKneeboard is displaying an overlay, if the overlay is hidden then everything will go back to looking normal. So the workaround is to bind "Show/hide" in Input settings and hide the overlay before pressing the "Start" button in Dirt Rally 2 until you are sitting in the car and can look around freely, after that you can unhide the overlay without any issues.
I have also added a clip from my stream showing the issue happening and it going away once I hide the overlay just before starting the stage (Sadly the overlay itself wasnt being captured in the stream) - [Twitch Clip](https://clips.twitch.tv/CrowdedHeadstrongClipsdadDBstyle-KrvXriZ9tAp-Q5uL)
Tested on a Reverb G2 using OpenComposite with OXRToolkit.

**Comment by fredemmott** [comment]
Copying from Discord:

> the two remaining possibilities would be:
> - the game is just weird and doing non-standard stuff: probably won't be fixed
> - OpenKneeboard needs to use the same D3D11 device as the game to copy its' graphics into the openxr pipeline; this changes its state. OpenKneeboard uses vrperfkit's code to save the state first, and restore it after, but IIRC mbucchia mentioned that OpenXR Toolkit's handling of this is more thorough. Switching it out /might/ fix it. This needs time + C++ knowledge to try

To set expectations, I don't spend much time with driving sims; OpenKneeboard is primarily intended for flight simulators. While not entirely unsupported, it might take a long time for me to get to this.

**Comment by fredemmott** [comment]
There should be a new msi at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/7387717910 in ~ 20 minutes. This *may* fix it.

Closing as:
- possibly fixed
- if not, probably falls into the 'just weird' category
- supporting OpenComposite is no longer a goal of OpenKneeboard

**Comment by fredemmott** [comment]
Slightly better version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/7388875154

**Comment by fredemmott** [comment]
Yeah, this is fixed in current nightly builds.
