### ISSUE TITLE
Feature Request: Separate position of second kneeboard

### ISSUE THREAD

**Issue by tanrr** [OpenKneeboard/OpenKneeboard#327]
Would be great to be able to position the second kneeboard separately, instead of its position mirroring the first kneeboard.

The mirrored position of a second kneeboard does work, but is often sub-optimal.  For example, in an F16, if I position the right kneeboard's non-maximized view to be a usable size and position without blocking my view of any important gauges, the mirrored left kneeboard (non-maximized) will block important gauges I need to be able to see.

**Comment by TaylorMonkey** [comment]
Came to leave the exact same feature request.  Another use case is having a captured browser/video window at slightly-below-eye level on one side, and having the second kneeboard actually on the knee.

**Comment by marksdoran** [comment]
Any chance this is getting near to the list of things to do soon??  This would be a big enhancement for my use case.

**Comment by fredemmott** [comment]
No updates, any updates will be posted here.

**Comment by wakevortex** [comment]
+1 for this request from me..it would be SO useful to be able to move the second kneeboard somewhere else in the VR cockpit rather than mirrored on the knee.. even if thats only in a config file somewhere ...
