### ISSUE TITLE
Window capture only updates when mouse moves or click on OpenKneeboard window

### ISSUE THREAD

**Issue by Diestur** [OpenKneeboard/OpenKneeboard#330]
Hi,

I am capturing 3 different windows (by exact name match) and the program picks them up fine (transparency and all).

Desktop (Windows 11):
But they ONLY update when mouse hovers over OKB's window capture preview.
It doesn't matter that OKB has the focus or not, or if its window is visible or hidden behind other ones or minimized.

VR:
I am using them In OpenXR, with 2 kneeboards enabled.
In VR the windows ONLY update when my gaze changes from one of them to the other.
If I gaze in and out of the same kneeboard it does not update at all.

I could understand that the design of the application is focused on static documents rather than live content, but the functionality is clearly already present.

Can I somehow (I tried looking for a config file with hidden/advanced settings) set up my desired refresh rate?

The window I am capturing runs at 5 fps, but if OKB has any constraint (performance wise or whatever) it'd still be wonderful if we could have it updating every 1 or 2 seconds.

I have not perceived any impact while moving my mouse to force it to be constantly updating its content.

**Comment by Diestur** [comment]
> What're the apps?

My 3 captured windows are overlays generated by RacelabApps

Funnily enough that app updated today, after my report, and I had to delete my tabs and create them again despite having the exact same name.
I don't bother about this edge case, but was interesting nevertheless.

> The refresh rate is almost entirely up to the app and Windows; OpenKneeboard updates whenever windows reports the app has a new frame - except that it's limited to 60fps.

I have made some tests, but I'm not managing to break it again at the moment.
My monitors have a quirk, they disconnect from Windows when turned off. And I do turn them off while in VR.
This causes the windows to move to the available monitor, or to be hidden when no displays (other than VR) are visible to Windows.
But I was already aware of this, so my original report was only after seeing the issue persist with both of them on (which made it possible to see OKB not updating its own window).

I'll keep using it and reporting back my findings.
Maybe it was Windows itself getting confused and not signalling the window update for some reason (I have not restarted the computer yet, only the VR and the apps).

> This isn't the case; Youtube videos in a browser are one of the most common use cases.

I'm new to this tool, only been using it for a week, judging by the documentation it looked 100% focused on showing .pdf files.
I'm really glad to hear that the app is way more capable than I thought.

> Do you have the mouse emulation enabled for these tabs? If so, do you have the same behavior when it is disabled?

No, the "Use tablet as mouse" toggle is not enabled.

**Comment by Diestur** [comment]
Ah, by the way (and sorry for the off-topic):

RacelabApps windows change size depending on the state of the game, and this requires me to click the "Reload all tabs" to see them correctly in OKB.

Is there a way to have this as a hotkey?
May this be related to the issue?
Could this, perhaps, be detected and reloaded automatically?

**Comment by Diestur** [comment]
For the record, I have not had the issue since my report.
I can get it 'stuck' (as in not updating anymore) when switching off the monitor, as the window gets minimized sometimes. So it does not update in OKB. But this makes perfect sense, and it works fine once I show (restore) the window again.


> I see this exact behaviour as well with RLA and iRacing. Sometimes it seems like the magnification of the captured window goes wrong somehow and the image is bigger than will fit in the kneeboard frame for the display so the result is a cropped version of the captured window content.

I don't know if it is the magnification or something along the lines that the iRating column is not shown in practice sessions, messing the size between practice/qualy/race.
Though I also see the bottom of the window cutting out in race sessions, so maybe you are right with the magnification.

Ideally we would have a toggle* to automatically reload the windows if the size changes.

*: I propose a toggle for this detection just in case it would break a different app/use case.

> Not yet :) I have submitted a code change for review to add this capability.
> 
> With luck this might be available in the next version of OpenKneeboard.

Wonderful news!!
My button box has a spot waiting for this trigger 😄

**Comment by Diestur** [comment]
Here is video proof of the issue!

This time it did not even update when changing the focused window in VR or when hovering or clicking with the mouse in the screen.

[2023-04-18 19-56-05.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/11264894/2023-04-18.19-56-05.zip)

The overlays worked fine during the Qualifying session, but they were cutting some lines (OKB overlay was too short for the actual window, and it looked stretched vertically).

When the game was transitioning to the Race session I reloaded All tabs and the size was correct.
I did not notice they were not updating until a while later, but they were stuck for the 25 minutes.

It is very important to note that this time my screens were ON all the time. So we can discard Windows going nuts when moving to the available display.

**Comment by fredemmott** [comment]
#336 for the size issue; for 'not updating without a mouse', could you share the logs:

Share your logs by:

1. Opening OpenKneeboard's Help page
2. Clicking "Save as..."
3. Saving the file somewhere handy
4. Sharing the file here

![image](https://user-images.githubusercontent.com/360927/235364042-157d4dc9-ff44-45e8-9cc7-4428210958a7.png)

**Comment by magnazan** [comment]
Pretty sure this is the same issue I reported #336

**Comment by Diestur** [comment]
Finally managed to reproduce the issue and catch it on video!!

[2023-05-03 18-45-04.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/11385012/2023-05-03.18-45-04.zip)

I was testing the resize for #336 when this happened.
I'm just spectating a race, no monitor unplugging or anything relevant.
I was just switching the driver on focus so the overlays would change their size.

As you can see in the video, using the nightly I don't have the button/link to copy the debug info.
Closing and opening OKB solves the issue.

**Comment by pedalracer** [comment]
Hello simracers,

I am using SimHub and a dashboard I load as 'windwo capture' in a a tab. Works fine until I restart OKB. Did you find a way that OKB auto captures the window again?
At the moment I have to delete and recreate a tab each day I want to race. Better would be I start Simhub and then OKB and all would be fine.

**Comment by fredemmott** [comment]
> As you can see in the video, using the nightly I don't have the button/link to copy the debug info.


![image](https://user-images.githubusercontent.com/360927/236221478-60e9038f-9dcf-4476-83ef-91d03875a3c8.png)

**Comment by fredemmott** [comment]
From Discord:

> it seems now i can reproduce the bug consistently. If i put a file on top at tab settings, when I open the program in vr the window capture tab will be updating at 1fps, no matter whats happening in this tab. If I reorder the tabs putting the window capture at top and restart the program it will be updating normally

**Comment by fredemmott** [comment]
The order doesn't appear to matter, however the act of reordering does

**Comment by fredemmott** [comment]
![Image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/3da034a2-3c4b-4a3b-93b7-41d881370bd3)

This shows that:
- the new frame event is reaching the `TabPage` as `TabPage::PaintLater` is called very frequently
- it is *not* reaching `KneeboardState`, as `gKneeboard->IsRepaintNeeded()` returns false; this is shown by traces including `TabPage::PaintLater` -> `FrameTick` -> "Prepared to render" , then `FrameTick` stopping without a corresponding "Kneeboard relocked"
