### ISSUE TITLE
DCS - "TheWay" v2 can't be captured

### ISSUE THREAD

**Issue by Quozl1** [OpenKneeboard/OpenKneeboard#331]
The program is TheWay for DCS, https://github.com/aronCiucu/DCSTheWay 

If I add it as a Tab and select window capture it adds it fine but none of the buttons in the program are clickable when trying to access them from openkneeboard. 

All other tabs that have been added for different programs work as intended with both the mouse and tablet pen working perfectly
EG in chrome etc. 

The program is a java program used to automatically enter waypoints in DCS from the F10 map and once selected send them to the game but currently no clicks are able to be registered when trying to use it in openkneeboard.

Have had another user confirm the same issue occours when they add TheWay to their tabs as well.
![theway nothing is clickable](https://user-images.githubusercontent.com/117060944/232235939-84f409fb-683d-4a79-9112-462d04b91cbd.JPG)
![theway](https://user-images.githubusercontent.com/117060944/232235957-1fb47411-0b13-47ca-924a-27c77c361c0f.JPG)

**Comment by fredemmott** [comment]
Are you still having this issue with v2, with is now using Electron instead of Java? Other Electron apps (like Discord) seem to work fine.

**Comment by Quozl1** [comment]
Yes, still having the issue with version 2. It will not show at all in
OpenKneeboard now. I can use it in DCS VR by using this workaround though.
I use the pointer from scratchpad and then using the keyboard shortcuts to
select and transfer the waypoints but if I add the program to openkneeboard
it doesn't show anything in the tab.

**Comment by Quozl1** [comment]
Yes, still having the issue with version 2. It will not show at all in OpenKneeboard now when in VR. 

I can use it in DCS VR by using the pointer from scratchpad and then using the keyboard shortcuts to select and transfer the waypoints but if I add the program to openkneeboard it doesn't show anything in the tab.

**Comment by fredemmott** [comment]
v2 appears to be entirely incompatible with Windows's capture support, so can't be supported by OpenKneeboard unless that changes.

There also isn't an obvious workaround like there is for UWP apps - TheWay has 3 windows, but none of them capture correctly

![image](https://user-images.githubusercontent.com/360927/235368849-08f513ab-f90f-4697-9571-46545a3e2f5d.png)

This is a TheWay/Chromimum/Windows limitation, not OpenKneeboard - for example, v2 also can't be captured by OBS.
