### ISSUE TITLE
Log location / troubleshooting

### ISSUE THREAD

**Issue by 9999years** [OpenKneeboard/OpenKneeboard#332]
Where are logs written to? Are they written in release builds at all?

I see `dprintf` statements throughout the code, like here:

https://github.com/OpenKneeboard/OpenKneeboard/blob/b1dac0416bfadc5dab868c5a7e567dd2884667c0/src/app/app-common/Tab/DCSBriefingTab.cpp#L120

But I can't figure out if they actually get written anywhere. I'd really like to see them! I can't get the DCS integration to work right -- adding a new tab manually to display images from a folder works, and it's all I _really_ need, but I'd like to be able to get radio message logs and mission briefings automatically.

**Comment by fredemmott** [comment]
- Help -> Debug
- the windows debug stream (e.g. https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)
- `C:\Program Files\OpenKneeboard\scripts\enable-log-files.reg` will enable writing them to Saved Games\OpenKneeboard

**Comment by fredemmott** [comment]
Also, https://openkneeboard.com/troubleshooting/dcs-tabs.html for the problem that led you there :)
