### ISSUE TITLE
Window capture sometimes doesn’t adjust correctly when window size changes

### ISSUE THREAD

**Issue by fredemmott** [OpenKneeboard/OpenKneeboard#336]
Windows provides the size along with the capture; currently unknown if windows provides the wrong size, or openkneeboard is somehow handling it correctly.

do not currently have a quick and reliable way to reproduce

**Comment by fredemmott** [comment]
Some brief discussion on discord:

![Uploading IMG_2478.jpeg…]()

**Comment by fredemmott** [comment]
![IMG_2478](https://user-images.githubusercontent.com/360927/235031830-07dd765b-2edb-4714-b0ce-ee43cf52a341.jpeg)

**Comment by magnazan** [comment]
The specific issue that I am able to reproduce is using Racelab app overlays with iRacing. What happens is before loading iRacing if OKB is open before Racelab apps there is no overlay open so there is a small yellow (default?) box where the overlay would be. When the iRacing session loads Racelab then opens the overlay to display the information (relative, standings etc) but the small yellow box that OKB opened does not resize to the Racelab overlay so it just shows a zoomed in square in the tab. I usually delay the opening of OKB until after Racelab and iRacing is in a session - however this issue happens when switch from a practice session to race session due to the overlay going and coming back again.

**Comment by magnazan** [comment]
So just an update to this as a test I forced the Racelab overlay to appear/reappear but with additional information after it reappears. I can see the yellow box around the overlay resize properly but in OKB it cuts off the additional information.

![Capture](https://user-images.githubusercontent.com/8119132/235277716-d52ef01d-1c5c-444a-9638-9875b424d5ee.JPG)

**Comment by fredemmott** [comment]
Okie, I've found one fast, reliable way for me to reproduce this without a game. I have:
- a normal DPI 1920x1080 monitor
- a high DPI 5120x1440 ultrawide
- both attached to the same graphics card

For me to reproduce:

1. Disable the ultrawide (e.g. via the windows+p presentation shortcut)
2. Launch OpenKneeboard on the 1080p 
3. Launch Chrome
4. start capturing chrome
5. enable the ultrawide as dual-monitor extended display (also doable via windows+p)
6. drag chrome window to ultrawide
7. drag right side of chrome window to make wider; OpenKneeboard updates to a certain point, which _looks like_ 1920, then it can reproduce this problem

**Comment by fredemmott** [comment]
... and the D3D11 debug layer gets very unhappy about this:

> ```
> D3D11 ERROR: ID3D11DeviceContext::CopySubresourceRegion: When offset by the destination coordinates, pSrcBox does not fit on the destination subresource. OffsetSrcBox = { left:0, top:0, front:0, right:2423, bottom:1033, back:1 }. DstSubresource = { left:0, top:0, front:0, right:1936, bottom:1056, back:1 }. [ RESOURCE_MANIPULATION ERROR #280: COPYSUBRESOURCEREGION_INVALIDSOURCEBOX]
> D3D11 ERROR: ID3D11DeviceContext::CopySubresourceRegion: pSrcBox is not a valid box for the source subresource. *pSrcBox = { left:0, top:0, front:0, right:2423, bottom:1033, back:1 }. SrcSubresource = { left:0, top:0, front:0, right:1936, bottom:1056, back:1 }. [ RESOURCE_MANIPULATION ERROR #280: COPYSUBRESOURCEREGION_INVALIDSOURCEBOX]
> ```

**Comment by fredemmott** [comment]
Windows is:
- telling me the window is 2423x1033
- giving me a 1936x1056 image

:/

**Comment by fredemmott** [comment]
Wheee

![image](https://user-images.githubusercontent.com/360927/235365400-fc9b3fa6-3f90-407a-9d9e-1ada3c73b74f.png)

**Comment by fredemmott** [comment]
Should be fixed in https://nightly.link/OpenKneeboard/OpenKneeboard/actions/artifacts/672865200.zip

**Comment by Diestur** [comment]
I'm using the last stable version, as I did not want to risk using the nightly without testing it before a race.

I'll try to test it in the nightly version.Can it be just installed on top of the one I have?
(I think I saw somewhere that it's better to first uninstall, but I cannot find that document for the life of me. So it could be for a different tool that I am mixing in my head)


**For an easy to reproduce bug (using RaceLab):**
- Capture the Standings screen
- Switch the driver in focus between one of the leaders to someone in the mid-field

As RaceLabs adds/removes the "Number of top drivers=3" rows the window size changes.
When the size decreases there is not problem with OpenKneeboard, but when it increases the window is cut-off.


[OpenKneeboard-v1.4.2.1399-2023-05-02-19-56 Wrong window size several times.txt](https://github.com/OpenKneeboard/OpenKneeboard/files/11376276/OpenKneeboard-v1.4.2.1399-2023-05-02-19-56.Wrong.window.size.several.times.txt)
[OpenKneeboard-v1.4.2.1399-2023-05-02-19-57 Wrong window size 2.txt](https://github.com/OpenKneeboard/OpenKneeboard/files/11376277/OpenKneeboard-v1.4.2.1399-2023-05-02-19-57.Wrong.window.size.2.txt)

**Comment by fredemmott** [comment]
Upgrades - including to nightlies, or from a current nightly to the next release - do not need an uninstall. Downgrading from the nightly back to the previous release will need an uninstall.

**Comment by magnazan** [comment]
> Should be fixed in https://nightly.link/OpenKneeboard/OpenKneeboard/actions/artifacts/672865200.zip

Tried using this but it just crashes when trying to edit the tabs :(

**Comment by fredemmott** [comment]
https://openkneeboard.com/troubleshooting/crashes-and-freezes.html

**Comment by fredemmott** [comment]
> When window gets smaller, I see a 1 pixel row at the bottom. Can be seen in my video in #330. (very bad quality, I know, I have already increase the quality of the recordings for future reports)

That seems to be part of the window itself, probably an alpha-blended border or similar; as windows is at least saying that's the case, doesn't seem like there's anything to do on openkneeboard's end
