### ISSUE TITLE
Feature Request(s) - More overlays and flexibility (Kneeboards?) for use with Sim Racing

### ISSUE THREAD

**Issue by magnazan** [OpenKneeboard/OpenKneeboard#337]
I realise this is hijacking the original design of OKB but it's been so useful for Simracing - specifically running overlays like Racelab with iRacing which don't support OpenXR. The current version of OKB doesn't allow for enough flexibility to run up to 4-5 overlays and in different areas of the screen (required depending on car).

Features requested for use with SimRacing

- More independent overlays (kneeboards?)
- Flexibility to move and fix the location of each overlay
- Ability to reload tabs via binding or auto refresh (overlays aren't always fixed sizes)
- Ability to select which overlays show/hide via binding

**Comment by fredemmott** [comment]
Thanks; closing as duplicate as these are existing requests:

> * More independent overlays (kneeboards?)

#250

> * Flexibility to move and fix the location of each overlay

#327

> * Ability to reload tabs via binding or auto refresh (overlays aren't always fixed sizes)

#274 and #336

> * Ability to select which overlays show/hide via binding

#217
