### ISSUE TITLE
No control when not looked at?

### ISSUE THREAD

**Issue by PickRelated** [OpenKneeboard/OpenKneeboard#340]
When you have two kneeboards - it is not always convenient for controls to be applied when kneeboard is not looked at. Hopefully it makes sense.

For instance, my OpenKneeboard shares controls with DCS. In my case when I switch view to F10 map - my page also changes.

Is there a chance we could separate setting
`Bindings and pen strokes affect the kneeboard you're looking at`
into
`Bindings affect the kneeboard you're looking at`
and
`Pen strokes affect the kneeboard you last looked at`
?

Or whatever makes sense. I don't use tablet, so I don't know what's best.

In this case we could bind, for example, VPC Constellation's scroll wheel to changing pages. Imagine how awesome it would be! ☺️

Pardon my English. I am non-native.

Thanks a ton!

**Comment by fredemmott** [comment]
Thanks - not quite the same request, but I'm going to merge this with #245 - it'll be best to address them as one (more flexible) feature
