### ISSUE TITLE
Feature request: E6B/flight computer tab

### ISSUE THREAD

**Issue by wraith444** [OpenKneeboard/OpenKneeboard#354]
Would it be possible to add a tab that functions as an E6B, either as a graphical "touch and drag" style manual flight computer or as a digital "type in the values and tap Calculate" sort of setup? This would be especially handy in warbirds when you need to rely on pilotage and dead reckoning for navigation purposes.

EDIT: I ran a brief search for other issues raising this suggestion and didn't find any; My apologies if this has been suggested before and I just didn't find it/its response.

**Comment by fredemmott** [comment]
Related to #67 but not the same thing

**Comment by peterb154** [comment]
+1

**Comment by bbirchnz** [comment]
This is something I've long wanted to work on. I have some vectors I started rendering a while ago for this, but at the time needed to make a library of all sorts of widgets to make it possible. @fredemmott did you ever settle on a UI library/lua kit that might make complex tabs easier?

**Comment by fredemmott** [comment]
There’s no support for Lua tabs yet (#240 ), but pulling in Dear Imgui is probably the way to go, both for C++ and potential future lua support

**Comment by fredemmott** [comment]
This would be fairly straightforward for anyone familiar with JavaScript to do for v1.9.9 or above, along the same lines as https://github.com/OpenKneeboard/Calculator-Plugin

Closing as this is best done as a plugin by someone familiar with this kind of tool, rather than adding to OpenKneeboard itself.
