### ISSUE TITLE
Crash when launching from Voice Attack with Discord Open and as a Window Capture Tab

### ISSUE THREAD

**Issue by 01g8r** [OpenKneeboard/OpenKneeboard#355]
I use VoiceAttack to launch a number of programs.  When I have Discord Open (in Administrator Mode or not) and set as a Windows Capture Tab in OpenKneeboard if I launch OpenKneeboard with VoiceAttack it immediately crashes.  If I launch with a desktop shortcut it opens normally.  I tried this with a new saved games folder and the behavior is the same.  As soon as I add Discord as a Window Capture Tab I get the crash on startup from VoiceAttack.  If you need more info or anything else let me know.  Thanks.

**Comment by fredemmott** [comment]
You probably want to try advanced settings -> elevation options, and set to always run as a normal user

If that doesn't work, can you share a dump? Details at https://openkneeboard.com/troubleshooting/crashes-and-freezes.html

**Comment by 01g8r** [comment]
I'll try that.  No dump is created.  I ran the reg file.

**Comment by 01g8r** [comment]
I'm already running OpenKneeboard set to "Run as normal user".

**Comment by fredemmott** [comment]
> I'll try that. No dump is created. I ran the reg file.

1. run reg file
2. run openkneeboard in a way that crashes

If that doesn't create a dump either in saved games or %LOCALAPPDATA%\CrashDumps, check it's not running in the background by checking task manager

If it's not , you can try also running `enable-log-files.reg` from the scripts folder, then you should see a log folder in your saved games after you next run openkneeboard

**Comment by 01g8r** [comment]
Nothing in CrashDumps from OpenKneeboard.  OpenKneeboard not running in task manager after crash.  Log attached.  
[OpenKneeboard-20230519T005757.7665999-1.4.3.1417-19688.log](https://github.com/OpenKneeboard/OpenKneeboard/files/11512566/OpenKneeboard-20230519T005757.7665999-1.4.3.1417-19688.log)

**Comment by fredemmott** [comment]
Do you have any developer tools installed? Visual Studio, WinDbg, or similar? This really looks like it's running in a way that 'should' dump, but perhaps that's being diverted

**Comment by 01g8r** [comment]
I don't believe so.  Basically just use DCS on this computer.  I run Process Lasso, but not much other out of the ordinary.  Let me turn all my normal DCS add on stuff off and try it.

**Comment by 01g8r** [comment]
I imagine it has something to do with VoiceAttack since the normal shortcut works, but when launched from VA it crashes.

**Comment by fredemmott** [comment]
Does it crash if you run it as administrator, without voice attack?

**Comment by 01g8r** [comment]
No.  Set as Run Elevated it opens fine.  I got a Crash Report after I turned some stuff off.  Trying to figure out what it is.  
[sndctrl.exe.18860.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/11512620/sndctrl.exe.18860.zip)

**Comment by 01g8r** [comment]
With it set as Elevate it launces ok from VoiceAttack with that other stuff turned off.

**Comment by fredemmott** [comment]
Try turning off 'run as normal user', and instead telling voice attack to run explorer.exe, with arguments `C:\Program Files\OpenKneeboard\bin\OpenKneeboardApp.exe`

**Comment by 01g8r** [comment]
Turned OK back to normal user.  Turned DCS SRS on and crash from VA launch came back.

Trying to run with arguments now.

**Comment by fredemmott** [comment]
> Trying to run with arguments now.

Just to be clear, run *explorer.exe* with the openkneeboard path as the argument, don't run openkneeboard with arguments

**Comment by 01g8r** [comment]
Understood

**Comment by 01g8r** [comment]
That worked!  Thanks.  Tested with everything back on.  OK set to Normal User.
