### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by MansM** [OpenKneeboard/OpenKneeboard#36]
As an open kneeboard enduser
I want to be able to auto update
In order to reduce manual work

Though a prompt before update would be appreciated

**Comment by fredemmott** [comment]
There's two practical approaches to this:

1. I publish through the Windows Store
2. I wait an indeterminate amount of time for this to be supported by MSIX installers


MSIX are Microsoft's recommended way to package modern windows apps, however they do not yet support auto-updates on released versions of Windows

Auto-update *can* be supported on insider builds of Windows 11 (https://docs.microsoft.com/en-us/windows/msix/app-installer/auto-update-and-repair--overview) - it's unclear (a) when this will be available in normal builds of windows 11 (b) if this will ever be made available for windows 10

**Comment by fredemmott** [comment]
MSIX is powerful, easy to use, but honestly is a little half-baked for lifecycle management outside of the windows store - as well as this, the ability to cross-sign and replace expiring code signing certificates is also currently a feature that only works on Windows 11 Insider Edition.

**Comment by MansM** [comment]
I would say park it for now because of reasoning above.

Maybe just do an GitHub api check for latest version on launch and give a prompt about the update.

**Comment by fredemmott** [comment]
No sign of that API moving, so done this by:
1. checking the github release API
2. if requested, downloading the msix
3. opening it as if double-clicked

Doing 2 & 3 explicitly as microsoft have disabled `ms-appinstaller:?source=` URIs for a few months now because of security issues
