### ISSUE TITLE
Support typing in vertical positions above eye level

### ISSUE THREAD

**Issue by danoveb** [OpenKneeboard/OpenKneeboard#361]
Cannot type in a negativ value in "Vertical distance from eye level, in meters". Take ages to use the arrows if you want the window in far distance.

**Comment by danoveb** [comment]
A Workaround should be to open registry or setting file and change the value there, but I haven't been able to figure out the location....

**Comment by fredemmott** [comment]
> A Workaround should be to open registry or setting file and change the value there, but I haven't been able to figure out the location....

`VR.json` inside the profile folder within `Saved Games\OpenKneeboard`

**Comment by fredemmott** [comment]
Thanks; this'll be fixed in v1.5 (and it should also support commas as a decimal separator in locales where that's appropriate)
