### ISSUE TITLE
F-16 folder in profile-kneeboard not found

### ISSUE THREAD

**Issue by ytdlder** [OpenKneeboard/OpenKneeboard#379]
Hi,

every other plane (FC3, FA-18, Ka-50, ...) works, but even though I've tried quite a few names (like the one from the Wiki: https://openkneeboard.com/features/dcs.html#the-dcs-aircraft-tab), none worked...

FA-16C_60
F-16C_50
F-16C
F-16C bl.50
F16C

Could you please tell me what the correct folder name is? And update the Wiki of course^^

Here are some other non-standard names:
P-51D-30-NA   ("P-51D" = 20-NA version)
Ka-50_3            (Ka-50 III)

Thanks!

**Comment by fredemmott** [comment]
Sorry, this isn’t a module I have - the documentation is based on multiple user reports. You can see the full path in the debug logs. You might be able to find help from others with the module on discord.

**Comment by fredemmott** [comment]
As an alternative to the debug log, if you install the test version from  https://nightly.link/OpenKneeboard/OpenKneeboard/actions/artifacts/784121520 , it will show where it's looking in the tabs list:

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/f59f526e-d099-4faa-a90f-9d758129ec08)
