### ISSUE TITLE
Open DCS Updater / Launcher GUI Utility in background prevents use of OpenKneeboard in DCS

### ISSUE THREAD

**Issue by Juxe91** [OpenKneeboard/OpenKneeboard#380]
If DCS is started via the DCS Updater / Launcher GUI Utility, Version 2.0.0.32, Build 7.3.2023 and the Launcher is open in the background, OpenKneeboard cannot be opened in DCS. 

The error could be reproduced by me. If I started DCS via the DCS Updater / Launcher GUI Utility and closed the Launcher before a complete start of DCS, OpenKneeboard could be opened in DCS without problems. 

This is my first bug report on GitHub; if you need more info, please let me know.

**Comment by fredemmott** [comment]
Sorry, I won't be able to take a look at this for a few weeks at least.

> If I started DCS via the DCS Updater / Launcher GUI Utility and closed the Launcher before a complete start of DCS, OpenKneeboard could be opened in DCS without problems.

Because of this, please also report this as a bug in the launcher. OpenKneeboard does not care if any other apps are running, and this rules out permission issues.

**Comment by fredemmott** [comment]
Please also add:
- non-vr, steamvr, openxr, or oculus api?
- which headset you're using
- MT or ST
- debug logs from open kneeboard

**Comment by fredemmott** [comment]
Closing: not reproducible and not enough information.
