### ISSUE TITLE
OpenKneeboard doesn't respect Huion orientation

### ISSUE THREAD

**Issue by j8s0n** [OpenKneeboard/OpenKneeboard#385]
I set my Huion H640P to have a 90 degree rotation, to put it in portrait mode, to match the kneeboard. In Windows the stylus sends the expected up/down/left/right directions, but in OpenKneeboard under DCS (latest MT with a Varjo Aero in OpenXR) things are off by 90 degrees.

**Comment by fredemmott** [comment]
Only use the rotation setting in openkneeboard.
