### ISSUE TITLE
Crash from 3Dconnexion driver when launching

### ISSUE THREAD

**Issue by kbastronomics** [OpenKneeboard/OpenKneeboard#427]
After upgrading both DCS to 2.9 and Open kneeboard to Open Kneeboard v1.6.1+gha.1485
Open Kneeboard crash on start up
per directions I renamed the Open Kneeboard folder in saved games and tried again
same result

if I start OKB in admin mode it will start but eventually fails as well
I don't' need admin mode normally,  i just tried it to see if it makes a difference

dump file is on my google drive,  was 500MB in size.
I haven't seen any reported issues at this point and i checked discord for any as well

[OpenKneeboard.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/13061950/OpenKneeboard.zip)
[Dump](https://drive.google.com/file/d/1EAATN0AUD0R7YkMNTuixGxc6rokqA8ty/view?usp=share_link)

ALso see this in event viewer

Faulting application name: OpenKneeboardApp.exe, version: 1.6.1.1485, time stamp: 0x6522afe4
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3570, time stamp: 0xda674bb7
Exception code: 0xc000027b
Fault offset: 0x000000000012dd42
Faulting process id: 0xa020
Faulting application start time: 0x01da046dd305c761
Faulting application path: C:\Program Files\OpenKneeboard\bin\OpenKneeboardApp.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: fdb8df18-179a-4552-8492-271eee2ede4a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fredemmott** [comment]
Thanks, especially for the full dump - that should make this *much* easier to fix. I should be able to take a look on Monday :)

**Comment by fredemmott** [comment]
The crashing call is being made by this, which appears to be related to a space mouse; do you have the same issue if you disable/uninstall this driver, or at least stop any related processes/services?

>     Information from resource tables:
>        CompanyName:      3Dconnexion, INC
>        ProductName:      3Dconnexion, INC SiFocusHook
>        InternalName:     SiFocusHook
>        OriginalFilename: SiFocusHook.dll

**Comment by kbastronomics** [comment]
Ok,  first thing I did was unplug the USB Dongle then un-installed the spacemouse software/driver and rebooted.
started OpenKneeboard OK, no crash.
started DCS and a instant mission and hit my hot key to bring up the knew board and nothing.
check the game setting,  was on AUTO,  changed to direct3d non-vr and then it worked.

I'm going to try to re-install the latest driver and see if the problem returns,   I can't live with my space mouse when working in Fusion360.

will update and if it crashed I'll get a fresh dump

**Comment by kbastronomics** [comment]
ok,  just installed the driver/software again and immediate crash when starting openkneeboard

dump is here
https://drive.google.com/file/d/1J3jEtZdAoBRCjXSMHiaGaqgnLTDHLmEF/view?usp=sharing

**Comment by fredemmott** [comment]
That crash is in the same place. Sorry, as this is a crash in their driver there's nothing I can do. It's probably best for you to:
- report to their support and ask for them to fix it
- also test with the WinUI3 Gallery app that I linked; if that also crashes, it's likely an incompatibility between their app and all/most WinUI3 apps, which are growing in popularity (including among built-in apps in Windows 11)
