### ISSUE TITLE
Enhancement/Request: Possibility to have an Output/Screenshot for "Endless Notebook" pages

### ISSUE THREAD

**Issue by flanker0ne** [OpenKneeboard/OpenKneeboard#438]
It will be a very nice feature, having the possibility to save the pages, tipically used as **_Endless Notebook_** like generic form or 9line 5line Checkin, for de-briefing purposes

**Comment by fredemmott** [comment]
Closing as duplicate of #192

**Comment by Burninator214** [comment]
Very disappointing to not be added as a feature
