### ISSUE TITLE
DPI issue with writing

### ISSUE THREAD

**Issue by AlexCaboose** [OpenKneeboard/OpenKneeboard#443]
You fixed an issue with the kneeboard in 4K being shifted up & left when I reported it about a month ago after a recent version update. I just noticed that when attempting to draw, at least with the mouse, the input is shifted up & left in the same way. I haven't tried with the wacom tablet yet. 

Quick gif of the issue: https://gyazo.com/d294518ddea950aca9a37fa9fdbe60a3

Logs: https://discord.com/channels/807359994856996915/1176296566110302308/1176297341540646982

**Comment by fredemmott** [comment]
I'm also seeing this on 4k monitors with system UI scaled for high DPI, but not on 100% scaling.

**Comment by AlexCaboose** [comment]
I'm using 150% scaling for reference on my monitor.

**Comment by fredemmott** [comment]
This is purely a mouse input problem in the GUI app:
- no problems with a tablet
- the cursor in the test viewer lines up with the drawing location
