### ISSUE TITLE
Per tab OpenKneeboard position

### ISSUE THREAD

**Issue by RangeyRover** [OpenKneeboard/OpenKneeboard#452]
Would it be feasible to be able to position tabs independently?
I'm using OpenKneeboard for simracing mainly.
For raceroom I have a large HUD, reHUD which is front and centre, it's a whole screen layout.
I'd also like to have my StreamDeck visible in VR, I use it for a button box.
I don't think I can have independent positions when using 2 kneeboards, or independent positions for tabs?
Thanks, This is a superb tool.

**Comment by fredemmott** [comment]
#327
