### ISSUE TITLE
Varjo: MSFS2020 D3D12 crashes with OK running

### ISSUE THREAD

**Issue by jonasrembratt** [OpenKneeboard/OpenKneeboard#469]
Repro:

1. Start Open Kneeboard
2. Start Microsoft Flight Simulator
3. In MSFS, switch to VR
4. Recenter
== MSFS crashes

I have no problems switching to VR in MSFS when Open Kneeboard is not running so appears to be related to OK somehow.

OK logs:
[OpenKneeboard-v1.6.4.1535-2024-01-02-10-17.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/13808558/OpenKneeboard-v1.6.4.1535-2024-01-02-10-17.zip)

**Comment by fredemmott** [comment]
This was fixed for the simulator with 0543e1e37f83738bffb61cb2bf9429e409627aaf and e79b2b922d772052ed515b8629ebb722b9248c39

**Comment by fredemmott** [comment]
Fixed more fully by https://github.com/OpenKneeboard/OpenKneeboard/commit/6f38db56946918e7eb783de54a2343ca2da6d0c2
