### ISSUE TITLE
Brightness Control

### ISSUE THREAD

**Issue by 000Ready000** [OpenKneeboard/OpenKneeboard#49]
Would it be possible to add a generic brightness control function to reduce brightness of pages when the kneeboard is open? The white background now cause glare on my headset lenses inside the headset. Also for night ops it would be nice to just be able to slide back the brightness.

Cheers, Ready

**Comment by fredemmott** [comment]
Yeah, there's a few ways to do this:

- replace the background white for PDF/text pages. Doesn't work for images
- configurable transparency. Avoids the glare, but can be extremely low contrast for nighttime
- paint over with black at variable transparency. Ditto, but probably a bit better
- a negative filter: black <-> white
- a B&W 'brightness' filter with controllable intensity. Effectively night vision for the kneeboard

'brightness' filter might be the most realistic, and the best one-shot

'negative' would be clear, but possibly too intense

A combination is probably the way to go:
- paint over with black to reduce glare/god rays: this is effectively 'multiply brightness by x%')
- brightness filter -> night mode. Recolor in green and it's a true night mode. Black background, white/green text

**Comment by 000Ready000** [comment]
Yeah for me it is whatever works. If there was some kind of dial to reduce the brightness, like almost all other light emitters inside the hog cockpit (except for the clock and that stupid UHF indicator on the front panel) that would be great because it can then be dialed back gradually as the evening starts to set in.

 

I do try to plan ahead because it does take quite some time making adjustments with the paint programs. I now sometimes use a negative filter (for example am using aerodrome plates in negative) and sometimes I have been putting a darker layer on top op images. I also created templates in night vision, like you said black background and green/white letters. 

 

For speed purposes it would be helpful if there was something inside the kneeboard to do all of this for you and take the work out of your hands. I frequently have to make last minute screen prints of MDCs because things change the last minute and I then don’t have the time to do any kind of filtering, because I am already starting.

**Comment by AndLindemann** [comment]
I noticed the same in MSFS. I use a text-file tab for taking ATC notes and on a night flight the white background is really super bright. As a workaround I'd just hide the kneeboard as I'd only expect complex ATC instructions pre-takeoff and after landing (clearance and taxi mostly), so there's no real reason to show the kneeboard during the flight.
But still adjustable brightness would be cool (of course the super bonus would be if cockpit lighting would affect the kneeboard, i.e. during the night you'd have to turn on your cockpit reading lights to see anything. But that might be a bit too much. :P

**Comment by franukis** [comment]
Would totally love to have the option of "NVG filter", it would make it consistent with the datacards I am generating for night missions (could share the C# code used for the filter if helpful, although I am a HW guy and the whole program is a mess from SW point of view)
![00_Datacard_HORNET1](https://user-images.githubusercontent.com/2131144/165902065-21d5bd59-4d85-492c-bdad-f705b344f0bb.png)
![00_Datacard_HORNET1](https://user-images.githubusercontent.com/2131144/165902255-31b90720-8390-4529-8212-ca1a45934cc2.png)

**Comment by fredemmott** [comment]
Any chance your C# is a wrapper for HLSL? That would be handy - otherwise I can easily do a simple tint.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/OpenKneeboard/pull/84 is very related: while that's just dealing with opacity/transparency, the way it works is by applying a tint - but the tint includes an alpha channel - it's `(1.0, 1.0, 1.0, 1.0) * opacity` - where `(1.0, 1.0, 1.0, 1.0)` is RGBA white as floats.

Simple dimming can be done by using a grey tint instead of white, or red/green for colors.

**Comment by 000Ready000** [comment]
I think the most practical is to create two functions: one to dim and one to add brightness, which then can be bound to a turning knob on the Hotas and be used the same way like the flashlight and NVG brightness controls in DCS. Adding color like red or green seems like a nice addition,  but still can be way too bright if used independently without brightness control. Please look how the flashlight inside DCS works. It has a brightness function and a green/white toggle.

**Comment by franukis** [comment]
I have just checked. I am using a 3rd party (open source project): https://www.codeproject.com/Articles/5527/Blending-of-images-raster-operations-and-basic-col 
I am using it to blend with an image of the green filter, with a gradient, as you can see above

**Comment by tanrr** [comment]
If this feature request goes in (hopefully as a brightness filter), would be great to expose it through the remote-control exe methods.  Would allow a quick VoiceAttack "Kneeboard Brighter" or "Kneeboard Dimmer" when a page is pulled up that isn't set for night.

**Comment by fredemmott** [comment]
Yeah, probably just going to do the 'make everything darker' approach.

After trying pen+paper with some high-end NVG, it seem likely that a 'realistic' effect would be 'blurry mess' :p

**Comment by fredemmott** [comment]
Would y'all prefer this to only affect in-game rendering, or both in-game and in-app?

**Comment by AndLindemann** [comment]
In-Game would be enough for me :)

**Comment by ytdlder** [comment]
If I may add to that:
the app already uses the systems light/dark mode.
A setting for the ingame kneeboard with the same effect would be really cool!
Playing in HDR makes the kneeboard super bright^^
