### ISSUE TITLE
OpenKneeboard-v1.7-alpha7

### ISSUE THREAD

**Issue by otherguy485** [OpenKneeboard/OpenKneeboard#500]
2 issues I have when using SteamVR as my OpenXR runtime and running iRacing.

1. I can add one tab, but when I go to add a 2nd tab the 1st tab that I could see in VR also goes away and I don't see either knee board.  I have tried uninstalling and reinstalling and setting everything back to default but the same thing keeps happening.
2. The other issue I have is my mouse pointer goes away on my screen and I can no longer see it, it is active as I can see things highlighting when I mouse over something, but I have to close OKB to actually see the pointer again.

This is running iRacing via OpenXR and SteamVR (set as XR runtime).
Anyone else seen this or have suggestions?

**Comment by fredemmott** [comment]
1) upgrade to alpha8 or downgrade to a stable version

2) if you are capturing iRacing, turn off input injection; otherwise, openkneeboard does not affect input; check settings in other apps that do.
