### ISSUE TITLE
OpenKneeboard v1.7-alpha8+gha.1804 (mouse pointer issue)

### ISSUE THREAD

**Issue by otherguy485** [OpenKneeboard/OpenKneeboard#501]
iRacing using OpenXR with SteamVR as my XR runtime.

Every time I hit the button to recenter my headset I loose the mouse pointer on my monitor.  I can see it all the time as long as I don't recenter my headset which sometimes I have to make slight adjustments to my headset center.

Basically if I have to recenter my headset, I can no longer move the Tabs because of no mouse pointer, unless I close and reopen OKB.

**Comment by fredemmott** [comment]
Recentering openkneeboard has mo affect on the mouse or other apps - check other apps, such as iRacing itself, for other actions bound to the same buttons

**Comment by fredemmott** [comment]
That said, what tabs? Openkneeboard - and openkneeboard tabs - do not support mouse control while in game, even before recentering.

**Comment by otherguy485** [comment]
So when I have OKB open and hit the recenter button on my wheel the mouse
pointer goes away on my monitor, I can see things "highlight" when I happen
to move over it, but can't see the pointer.  This is on my monitor not in
game, I am not trying to control anything in OKB with my mouse, just see it
on my monitor to click things.

**Comment by otherguy485** [comment]
Do I need to turn on "The Windows mouse cursor is not captured" option to
make it work better?
[image: image.png]

**Comment by otherguy485** [comment]
Is what I am saying making sense?  Just want to make sure the issue is understood and I am not making it confusing.

**Comment by fredemmott** [comment]
OpenKneeboard never affects the windows mouse cursor; the capture option just chooses whether or not it's included visually. This is because the Windows mouse cursor will always affect the top-most windows, which isn't generally what's wanted here.

If you're not seeing OpenKneeboard's own cursor, this sounds like the same issue as #491
