### ISSUE TITLE
v1.7: improve image quality on Varjo

### ISSUE THREAD

**Issue by fizzle77** [OpenKneeboard/OpenKneeboard#510]
Varjo's native image scaling is lackluster and unlikely to improve for the Aero. Super-sampling in OpenKneeboard would improve the situation somewhat.

[Related Discord conversation](https://discord.com/channels/807359994856996915/1171049696018567219/1211449503945850930).

**Comment by fredemmott** [comment]
This would be better solved by #503, but this requires manufacturers to add support for the `XR_META_recommended_layer_resolution` extension; it is not currently supported by any PCVR runtime.
