### ISSUE TITLE
VR position settings don't unlock when recentering with bound button.

### ISSUE THREAD

**Issue by fizzle77** [OpenKneeboard/OpenKneeboard#513]
In 1.7, the VR position settings aren't unlocked when recentering via the bound button. Pressing the `Recenter now` button here will unlock the position settings as expected, but pressing the recenter binding will not.

![center-not-known](https://github.com/OpenKneeboard/OpenKneeboard/assets/42720583/fb6dc47f-dade-4662-8933-f24fccb03c2e)

**Comment by fizzle77** [comment]
Okay after some testing with 1.6.4 and the latest 1.7 I think I understand what's happening.

In 1.6.4, it looks like those position setting controls are never disabled, and the recenter button and accompanying text are there as an advisory. What I **thought** was happening was that OpenKneeboard remembered that I had centered the view when I first started DCS, and enabled these settings then.

In 1.7, you disable those controls by default. I center the view in VR when first entering DCS, but when I go to that settings page later, the controls are disabled. If I center again (even with the bound button), they are enabled. This is fine, but it would be handy if it remembered I'd already centered the view and enabled the position settings then.

(I think this obviates the need for the debug info zip, let me know if not.)

**Comment by fredemmott** [comment]
Yep - this is new behavior in v1.7 as the warning is not enough ("My kneeboard is invisible because I put it behind my head" is still a common problem with v1.6). Needing it a second time is also intentional because taking off some headsets makes recentering again necessary.
