### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mohsenkondori** [OpenKneeboard/OpenKneeboard#515]
I get this build error, How to solve it? @fredemmott 
ninja: error: 'third-party/directxtexEP-prefix/Release/lib/DirectXTex.lib', needed by 'src/utilities/OpenKneeboard-Viewer.exe', missing and no known rule to make it

Thanks

**Comment by fredemmott** [comment]
Ninja is incompatible, you must use the visual studio cmake generator instead

**Comment by fredemmott** [comment]
There’s https://openkneeboard.com/internals/README.html#building 

there’s also somewhat more verbose steps at https://github.com/OpenKneeboard/OpenKneeboard/blob/master/.github/workflows/ci.yml

**Comment by fredemmott** [comment]
Sorry, I've not seen those errors before, and it builds on a clean install of windows and visual studio.

It looks like you're trying to build is as part of another project which is mostly using MSVC 2019 - try a standalone build, but then you need to look at the integration.

Also, if you are building it as part of 'qtquick3dxr67' and that project is ever sold or distributed in any form, that project will need to have source code available under the same license as OpenKneeboard itself.

**Comment by fredemmott** [comment]
There are general reports - not tied to OpenKneeboard - that FTK1011 may be sometimes caused by long build paths; from your screenshot, this seems like a plausible possibility.

**Comment by fredemmott** [comment]
The API layer is only supported as part of OpenKneeboard itself; see https://openkneeboard.com/ for end user documentation.

OpenKneeboard and the API layer are not an SDK, and not supported as one.

**Comment by fredemmott** [comment]
Also worth noting that the API layer is under the same license as the rest of OpenKneeboard, which is GPL v2 with one specific additional linking exemption.

**Comment by fredemmott** [comment]
If your needs include distributing a derived work of both qtquick3dxr and OpenKneeboard, it does not meet your needs, unless you obtained a a different OpenKneeboard-compatible license for qtquick3dxr than is noted on https://git.qt.io/annichol/qtquick3dxr. OpenKneeboard is not compatible with the Qt Commercial License, and OpenKneeboard intentionally does not allow 'any later version', so is incompatible with GPLv3.

If any use/distribution you plan would meet the license requirements that's of course fine, but:
- I do not offer any help or support for use as an SDK; this includes build issues
- I do not offer any end-user support for users of the API layer who may be using it via a different 'feeder' program
- backwards/forwards API/ABI stability is not a goal, and will not be one
- dependencies (including compiler requirements, C++/winrt, etc) will continue to change based on what's most convenient for the app as a whole
- while contributions are very welcome, they will be weighed against maintenance burden and relevance; this means they should stay fairly closely related to OpenKneeboard's primary purpose

**Comment by fredemmott** [comment]
It looks like you’re trying to install without building all targets; this isn’t supported.

openkneeboard’s build automatically fetches and builds all dependencies beyond those included with visual studio.

**Comment by fredemmott** [comment]
There is no SDK; you can use the openkneeboard app and a window capture tab or web dashboard tab

**Comment by fredemmott** [comment]
Web dashboard tab will potentially give the best results as transparency is easy (just use CSS to set the body as transparent )

**Comment by fredemmott** [comment]
If you do end up using the layer directly (not supported), please rename your copy to avoid conflicts and confusion; this should include both the “OpenKneeboard” and “FREDEMMOTT” parts of the name. “FREDEMMOTT” can be replaced with your own openxr vendor tag if you register one (see openxr docs), or “NOVENDOR” has became an unofficial standard

**Comment by fredemmott** [comment]
In general, there's a distinction between 'app-common' and 'app-winui3'; the UI is mostly constrained to the latter. This split was introduced a few years back when moving from WxWidgets to WinUI3. You need to rewrite everything in app-winui3 and figure out how to integrate the build system.

The 'common' parts still require the Win/RT event system.

That said, this isn't a change I'd be interested in merging, and OpenKneeboard is not supported as an SDK. Locking as your use case is off-topic for this repository and the proejct as a whole.
