### ISSUE TITLE
Problem OpenKneeboard and SteamVR

### ISSUE THREAD

**Issue by Bikeman47th** [OpenKneeboard/OpenKneeboard#531]
Hi all

When OpenKneeboard is running, Falcon BMS does not register with the SteamVR app. Normally, SteamVR shows the application currently running, with OKboard running it does not. Included is the error log, hope this helps.

Anyway, many thanks for the great work.
Bikeman

[OpenKneeboard-v1.7.1.1911-2024-03-12-23-07.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/14579276/OpenKneeboard-v1.7.1.1911-2024-03-12-23-07.zip)

**Comment by fredemmott** [comment]
Looks like GitHub's having trouble with that download - could you re-upload?

- if Falcon BMS is in OpenKneeboard's game settings as 'auto-detect', switch it to SteamVR
- make sure everything's running on the same CPU

**Comment by Bikeman47th** [comment]
Hi Fred

I'll upload it again as soon as I am at my PC. Tnx for the hint with auto-detect, I'll give it a try.

Regards
Bikeman

Von: Fred Emmott ***@***.***>
Gesendet: Dienstag, 12. März 2024 23:42
An: OpenKneeboard/OpenKneeboard ***@***.***>
Cc: Bikeman47th ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenKneeboard/OpenKneeboard] Problem OpenKneeboard and SteamVR (Issue #531)


Looks like GitHub's having trouble with that download - could you re-upload?

Other than that:

  *   if Falcon BMS is in OpenKneeboard's game settings as 'auto-detect', switch it to SteamVR
  *   make sure everything's running on the same GPU

-

**Comment by fredemmott** [comment]
If setting it to SteamVR doesn't fix it, can you try the version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8266146931 ? Download links at the bottom.

**Comment by Bikeman47th** [comment]
I'll try that. Attached find the logfile. Btw, the problem only occurred after the last update.


Von: Fred Emmott ***@***.***>
Gesendet: Mittwoch, 13. März 2024 16:14
An: OpenKneeboard/OpenKneeboard ***@***.***>
Cc: Bikeman47th ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenKneeboard/OpenKneeboard] Problem OpenKneeboard and SteamVR (Issue #531)


If setting it to SteamVR doesn't fix it, can you try the version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8266146931 ? Download links at the bottom.

-

**Comment by Bikeman47th** [comment]
Installed 1.71. and managed to set to SteamVR. Did not do it correctly the first time round. Works as designed! Sorry for the confusion.

Regards
Bikeman

Von: Fred Emmott ***@***.***>
Gesendet: Mittwoch, 13. März 2024 16:14
An: OpenKneeboard/OpenKneeboard ***@***.***>
Cc: Bikeman47th ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenKneeboard/OpenKneeboard] Problem OpenKneeboard and SteamVR (Issue #531)


If setting it to SteamVR doesn't fix it, can you try the version at https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8266146931 ? Download links at the bottom.

-
