### ISSUE TITLE
OpenKneeboard is looking for the wrong AH-64D folder

### ISSUE THREAD

**Issue by GussyH** [OpenKneeboard/OpenKneeboard#569]
OK is looking for a folder called 'AH-64D_BLK_II'. However the module installs in a folder called 'AH-64D'.

OK therefore doesn't find content for the Aircraft tab correctly.

I've had to name my folder in Saved Games to match what OK is looking for rather than the 'installed' module folder name.

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/19994285/ebc89568-6861-489f-bffe-8587c5528cc5)

**Comment by fredemmott** [comment]
Thanks! Is it just the one variant?

Could you try adding it to the mapping following the instructions at https://openkneeboard.com/troubleshooting/dcs-tabs.html#the-path-is-incorrect-for-some-aircraft ? If that works, I'll add the change to the next version

**Comment by GussyH** [comment]
As far as I'm aware there's only 1 variant.

Adding the following to the mapping

`"AH-64D_BLK_II": "AH-64D"`

Results in

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/19994285/32a02f4f-fdab-4844-9e38-00287683b121)

**Comment by fredemmott** [comment]
That looks correct - are the files you expect being shown?

**Comment by fredemmott** [comment]
Though perhaps it should change to try both for saved games, depending on what DCS’s built in kneeboard does

**Comment by GussyH** [comment]
Probably just needs the mapping, and the line in the docs to warn people of the exception, just like the F-16?

**Comment by fredemmott** [comment]
Yeah, from https://www.digitalcombatsimulator.com/en/files/3331003/ it sounds like the saved games path is correct

**Comment by fredemmott** [comment]
While the path is corrected, built-in kneeboard pages will not be loaded for this aircraft, as OpenKneeboard only supports built-in kneeboard **images**; the AH-64D built-in kneeboard is custom Lua files, which are not supported.

**Comment by GussyH** [comment]
> While the path is corrected, built-in kneeboard pages will not be loaded for this aircraft, as OpenKneeboard only supports built-in kneeboard **images**; the AH-64D built-in kneeboard is custom Lua files, which are not supported.

Yes I realise that. Not a problem :)
