### ISSUE TITLE
Dual wielding kneeboards?

### ISSUE THREAD

**Issue by Orrrb** [OpenKneeboard/OpenKneeboard#57]
Just a thought. Would it be feasible to get two instances of the kneeboard running at the same time?

**Comment by fredemmott** [comment]
For the first two, there's another choice where it's unclear which option is best:
- two 'views' of the same set of tabs/pages, just with a different current page/tab
- entirely separate; tabs/pages aren't shared. If they happen to both include the same file, graphics tablet doodles/notes aren't shared

Would probably start with the first

**Comment by iantron** [comment]
I'll suggest an extension. I'm assuming you'd end up with the "entirely separate...doodles/notes aren't shared" implementation, but a neat feature would be to move a notebook/chapter from one kneeboard to the other and back, while _preserving_ the drawings.

**Comment by PickRelated** [comment]
If I might suggest - you might control pages and tabs while gazing at the kneeboard. This will allow you to have as many copies as you want with the same key bindings.

**Comment by fredemmott** [comment]
While I don't plan to add this to the main app, it'd be good to architect this to support an arbitrary number of layers in arbitrary positions; this would allow the steamvr/openxr/oculus implementations to be used for less specialized tools (e.g. embedding arbitrary windows without the 'kneeboard' concept)

**Comment by fredemmott** [comment]
- [ ] multiple shared textures and layer configurations (SHM)
- [ ] populate multiple layers
- [ ] render multiple layers
- [x] distinguish pen events and downstream events by kneeboard - e.g. page changes triggered by tapping a PDF hyperlink
- [ ] 'active kneeboard' detection (gaze)

**Comment by fredemmott** [comment]
Complete as of v1.1-beta2 ; please open separate issues for any bugs or feature requests
