### ISSUE TITLE
App container error

### ISSUE THREAD

**Issue by mohsenkondori** [OpenKneeboard/OpenKneeboard#570]
When I run the OpenKneeboarApp.exe, I get the bellow error:
![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/50166193/ca082dfb-9fee-41df-b7d4-dc3b0d57f274)

System Information:
![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/50166193/63c3a624-e7bf-4240-ad71-efbb8cb204e6)

**Comment by fredemmott** [comment]
What version is this? This looks like a self build, outside the usual source tree, and running as administrator

**Comment by fredemmott** [comment]
Regardless, it appears the version of windows you are using is not supported by the windows app sdk, which is the source of this error. Openkneeboard does not require an app container, but it does require windows 10 or 11

**Comment by fredemmott** [comment]
More specifically:
- the latest version of Windows 2016 server is 1607 (10.0.14393.6897)
- the windows app sdk requires 1809 (10.0.17763)
- OpenKneeboard itself needs 10.0.20348.0 for the Windows::Graphics::Capture APIs and various newer Direct3D features that I wouldn't expected to be backported to a server edition of windows
