### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by mohsenkondori** [OpenKneeboard/OpenKneeboard#573]
The OpenKneeboard use more than 10% cpu when I edit (change rotate, position, zoom, opacity, ...), how I can decrease it?
CPU: 12th Gen Intel(R) Core(TM) i7 - 12th
GPU: Radeon RX 580 Series

**Comment by fredemmott** [comment]
These are rare operations (generally configured once, then never changed again), which aren't a priority to optimize. Your first steps would be to use a profiler to find out where the CPU time is being spent.
