### ISSUE TITLE
OpenKneeboard crash when loading DCS mission

### ISSUE THREAD

**Issue by ytdlder** [OpenKneeboard/OpenKneeboard#574]
(other OpenXR apps are fine)

OKB crashes every time. Even restarting the app while DCS is running, it opens but immediately crashes again.

crashdumps and logs are attached.
[OKB log and dumps.zip](https://github.com/OpenKneeboard/OpenKneeboard/files/15133119/OKB.log.and.dumps.zip)

**Comment by fredemmott** [comment]
Could you load `C:\Program Files\OpenKneeboard\scripts\enable-log-files.reg` , cause another crash, then share the latest file in `Saved Games\OpenKneeboard\logs` please?

**Comment by fredemmott** [comment]
Also `enable-full-dumps.reg` from the same folder, then after another crash, a dump from `%LOCALAPPDATA%\crashdumps` - there's sadly not enough information in the mini dumps to see what's going on

**Comment by fredemmott** [comment]
Finally, do you also get crashes if OpenKneeboard is enabled, but your other API layers (XRNeckSafer in particular) are disabled?

**Comment by fredemmott** [comment]
Need the full dump to see specifics, but have you tried different missions?

These are all crashing in the mission loading code; if built-in missions aren't crashing, a copy of the mission you're loading would be useful, but the full dump would be useful either way.

**Comment by ytdlder** [comment]
Hi,
will do!
Cheers :-)

**Comment by ytdlder** [comment]
Hm, that's weird, now after enabling those 2 registry settings, DCS crashes when getting into the plane. PC restart didn't help either...
Gonna get back to you

**Comment by fredemmott** [comment]
Those settings have absolutely no effect on the part of OpenKneeboard that loads in to DCS - something else is going on :(

**Comment by ytdlder** [comment]
Yeah, but its really weird; just played DCS for about 6h.
After that I posted the bug with OKB.
Then wanted to try what you suggested... and DCS isn't working anymore.

**Comment by ytdlder** [comment]
Man, THAT was weird... last time I've tried everything. chkdsk, sfc, dism for Windows. Removing all mods/scripts and checking the DCS files via Steam.
Nothing worked.

Tried again today and works like nothing ever happened... o_O

Anyhow, I've reproduced the issue and it's not the mission, but the campaign. I've tried a few missions loaded into the ME and starting them directly and OKB works just fine.
Only when played from the Campaign it crashes.

Here's the full log, dump and the campaign.

**Comment by ytdlder** [comment]
Hm, only 25MB allowed

**Comment by ytdlder** [comment]
Can you download the ZIP from this link?
https://drive.google.com/file/d/1ClWy1yfg3rV-h6zsq2P0lfXgr0cGztIz/view?usp=drive_link

**Comment by fredemmott** [comment]
@ytdlder you should have an access request in your email

**Comment by fredemmott** [comment]
Huh, looks like these missions were created with something other than the DCS mission editor. That's weird. Should be a straightforward fix though.

**Comment by fredemmott** [comment]
This should be fixed by the msi at the bottom of <https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/8878586538> , though that branch is not thoroughly tested - if it works, I'll probably put the fix into 1.8.3

**Comment by ytdlder** [comment]
so... this isn't something one can fix in the .cmp file itself? But thanks, I'll try it out!

**Comment by ytdlder** [comment]
Yep, this version (1.9.0) works with that campaign.
But what was the problem? Nothing on my end I could've fixed via editing the campaign data?

Thanks again!

**Comment by fredemmott** [comment]
The main mission lua directly references image files instead of going via an l10n/mapResource file.
