### ISSUE TITLE
Switching profiles does not apply the profiles' DirectInput bindings

### ISSUE THREAD

**Issue by callsigncacique** [OpenKneeboard/OpenKneeboard#584]
The binds are not independent per profile.

If you have multiple profiles, you can recreate the issue by creating a bind for profile B, and then you can switch to profile C and it will show that same bind.  Neither profile B or C are the default profile.   If  you remove the bind from profile c it will remove the bind in profile B.   
I tried uninstalling the app and deleting the openkneeboard folder from the saved games folder and installing the latest app.  The app would start with a complete fresh installation.  I created multiple profiles, then attempted to bind only one bind to the keyboard using a non-default profile, profile B.  Then i would switch to profile C and see that the bind for profile B applied to profile C as well.

see youtube link for video of issue: https://youtu.be/lVVnjcXV9vE

**Comment by fredemmott** [comment]
Bindings are saved per-profile, but switching profiles doesn't switch bindings; if you switch profile then restart OpenKneeboard, it will use the correct bindings for that profile

**Comment by fredemmott** [comment]
didn't notice this when testing as tablet bindings are handled correctly
