### ISSUE TITLE
Support Kneeboard Live?

### ISSUE THREAD

**Issue by GussyH** [OpenKneeboard/OpenKneeboard#585]
https://kneeboard.live/

This looks pretty interesting - interactive checklists

Would there be some way to get this to work inside an openkneeboard tab?

**Comment by fredemmott** [comment]
This would be possible for kneeboard live to add if https://github.com/OpenKneeboard/OpenKneeboard/issues/240 is done. Any updates on openkneeboard’s side will be there.
