### ISSUE TITLE
32-bit OpenXR API layer

### ISSUE THREAD

**Issue by Detegr** [OpenKneeboard/OpenKneeboard#588]
Hi.

I'm an author of a [VR plugin](https://github.com/Detegr/openRBRVR) for Richard Burns Rally. OpenKneeboard works great with SteamVR, however for OpenXR a 32-bit build of the API layer would be needed to get it to work as RBR is a 32-bit process.

I attempted naively to build the `OpenKneeboard-OpenXR` project with `Win32` as a target, but it failed to multiple static asserts and such.

**Comment by fredemmott** [comment]
FYI the majority of openxr runtimes do not support 32-bit, but this shouldn’t be too hard to do.

**Comment by fredemmott** [comment]
Ooh, this is a pile of fun :D

There's:
- my own use of size_t
- changing struct member alignment/padding between bitness
- static asserts in my code
- ... all of the above for everything related to OpenXR, D3D11, and Vulkan.

**Comment by fredemmott** [comment]
The biggest problem is this inside the vulkan headers:

```C++
#ifndef VK_DEFINE_NON_DISPATCHABLE_HANDLE
    #if (VK_USE_64_BIT_PTR_DEFINES==1)
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *(object);
    #else
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t (object);
    #endif
#endif
```

This means that for 64-bit builds, different handles (e.g. `VkCommandPool` and `VkPipeline`) are distinct C++ types, but for 32-bit builds, both are considered the same type so overloads are amibiguous.

**Comment by Detegr** [comment]
> FYI the majority of openxr runtimes do not support 32-bit, but this shouldn’t be too hard to do for the ones that do.

I'm aware of the [compatibility](https://github.com/Detegr/openRBRVR/blob/master/FAQ.md#can-i-use-openxr-instead-of-openvrsteamvr). Varjo and SteamVR runtimes are the only ones not supported that I know of.

Seems like it should be quite straightforward, but potentially tedious. Please let me know if I can be of some help :)

**Comment by fredemmott** [comment]
aaaand exactly the same needed for OpenXR:

```C++
#if !defined(XR_DEFINE_HANDLE)
#if (XR_PTR_SIZE == 8)
    #define XR_DEFINE_HANDLE(object) typedef struct object##_T* object;
#else
    #define XR_DEFINE_HANDLE(object) typedef uint64_t object;
#endif
#endif
```

**Comment by fredemmott** [comment]
@Detegr should have a 32-bit layer relatively soon, but it looks like your plugin will also need changes: `XR_KHR_vulkan_enable2` is required - in particular, use of `xrCreateVulkanInstanceKHR()`.

https://openkneeboard.com/compatibility/games.html#game-compatibility

**Comment by fredemmott** [comment]
With that, a 32-bit layer *DLL* is buildable but untested. Remaining work on OpenKneeboard's end:
- for backwards compatibility, stop the dual-arch logic from adding a '64' suffix to this DLL (otherwise there'll also be a lot more need for installer testing)
- also create separate JSON file for the 32-bit and 64-bit builds
- update the UI and enable/disable helper to support both the 32-bit and 64-bit layers
- update the installer to enable both the 32-bit and 64-bit layers by default
- testing and bugfixing :D

To build:

```C++
diff --git a/dualarch.cmake b/dualarch.cmake
index de230d0b..03ff07f0 100644
--- a/dualarch.cmake
+++ b/dualarch.cmake
@@ -1,5 +1,6 @@
 set(
   DUAL_ARCH_COMPONENTS
+  OpenKneeboard-OpenXR
   OpenKneeboard-WindowCaptureHook
   OpenKneeboard-WindowCaptureHook-Helper
   OpenKneeboard-c-api
```

**Comment by Detegr** [comment]
Whoa, that was fast, thank you! I do have the needed changes for `XR_KHR_vulkan_enable2` in the `develop` branch so we should be good to go.

**Comment by Detegr** [comment]
I built the 32-bit dll, and copied the json and dll to the OpenKneeboard's bin directory (1.8.2 installation). When launching the game I'm getting the following message via DebugView:
```
83	10.876259	19980	RichardBurnsRally_SSE.exe	Error [GENERAL | xrCreateInstance | OpenXR-Loader] : ApiLayerInterface::LoadApiLayers skipping layer XR_APILAYER_FREDEMMOTT_OpenKneeboard because negotiation function OpenKneeboard_xrNegotiateLoaderApiLayerInterface was not found
```

Here's output of `dumpbin`:
```
Dump of file C:\Program Files\OpenKneeboard\bin\OpenKneeboard-OpenXR32.dll

File Type: DLL

  Section contains the following exports for OpenKneeboard-OpenXR32.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           1 number of functions
           1 number of names

    ordinal hint RVA      name

          1    0 00016420 _OpenKneeboard_xrNegotiateLoaderApiLayerInterface@12

  Summary

        E000 .data
       3F000 .rdata
        7000 .reloc
        1000 .rsrc
       6D000 .text
 ```

Have I done something obviously wrong? Can this work on top of 1.8.2 or should I build the whole thing from `master`?

**Comment by Detegr** [comment]
Ah, `__stdcall` causes the name to still be mangled slightly so OpenXR loader does not find it. Slapping `#pragma comment(linker, "/EXPORT:" __FUNCTION__"=" __FUNCDNAME__)` into the function ([from stackoverflow](https://stackoverflow.com/questions/2804893/c-dll-export-decorated-mangled-names)) seems to make it export correctly, but it does not feel like the right solution.

With that the API layer seems to load but still I see nothing in game.

**Comment by fredemmott** [comment]
Entirely using master; I won't be attempting to bring this into 1.8

**Comment by fredemmott** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/export-exports-a-function?view=msvc-170#remarks has a few notes for the mangling.

Trying to find the 'best' way, and wasted a bunch of time: turns out CMake doesn't correctly determine what needs rebuilding when relevant .def sources or options are changed; need to delete part of the build tree to actually see changes.

**Comment by fredemmott** [comment]
Okie, assuming github actions passes, this is built and the symbol is exported, but on my end, it's **completely** untested for now. Will revisit in a bit.

**Comment by fredemmott** [comment]
![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/9ec7237a-588d-45a5-bdb6-a6c254bf3bf8)

Something's up in the IPC even without VR, most likely a struct layout/size difference.

**Comment by fredemmott** [comment]
Yep:

```
[2024-06-01 19:12:18 OpenKneeboardApp.exe (21084)] OpenKneeboard-WinUI3: Initializing SHM of size 2208 at `com.openkneeboard/1.9.0.0-s8a0`
[2024-06-01 19:12:27 OpenKneeboard-Viewer32.exe (15056)] OpenKneeboard-Viewer: Initializing SHM of size 2192 at `com.openkneeboard/1.9.0.0-s890`
```

**Comment by fredemmott** [comment]
`HANDLE` is 64-bit in 64-bit builds, 32-bit in 32-bit builds, but only 32-bits matter: https://learn.microsoft.com/en-us/windows/win32/winprog64/interprocess-communication

**Comment by fredemmott** [comment]
![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/4381bbcd-e61d-4394-b670-f773a0b05aaf)


There we go (at least for the viewer), though I apparently have different alpha blending set up in my Vulkan implementation as visible in the footer

**Comment by fredemmott** [comment]
This is now working with a 32-bit hello_xr with `-G D3D11`, `-G D3D12`, and `-G Vulkan2`

**Comment by Detegr** [comment]
Thank you! Installed the version from GitHub actions and it works flawlessly 🎉
