### ISSUE TITLE
Add ability to bind mouse buttons

### ISSUE THREAD

**Issue by AndLindemann** [OpenKneeboard/OpenKneeboard#59]
I'd like to have the ability to bind mouse buttons in the same way as I can bind keyboard/tablet/joystick buttons.
Mouse is being used heavily i.e. when flying MSFS airliners and I hence have bound my VR viewpoint reset to mouse 5 and would want to couple the "Recenter Kneeboard" binding with it.

**Comment by fredemmott** [comment]
It is surprisingly common for people to accidentally bind left-click to recentering; for this reason, future versions will have this feature disabled by default, but it can be re-enabled in advanced settings:

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/360927/91704887-6b7d-4d46-b853-89dec5278016)
