### ISSUE TITLE
OpenKneeboard crashes if it attempts to load an invalid PDF

### ISSUE THREAD

**Issue by Lemonade137** [OpenKneeboard/OpenKneeboard#591]
When adding a File type tab of a .pdf or a Folder type tab containing a .pdf document OpenKneeboard crashes and will not open until the Saved Games/OpenKneeboard folder is reset

OKB crash dump: https://drive.google.com/file/d/1VVy3qKFbw4OCRN7eRepHhhZFByLaun52/view?usp=sharing

Saved Games/OpenKneeboard folder pre-crash: https://drive.google.com/file/d/1yLJJKLMKjOfnbTpBb1d5bvU8K1RbE-JU/view?usp=sharing

Saved Games/OpenKneeboard folder post-crash: https://drive.google.com/file/d/1jeo3hrN-hFpV39ndRcZ5r89_FsOZjVSh/view?usp=sharing

**Comment by Lemonade137** [comment]
[AH-94 Dragonfly Manual.pdf](https://github.com/user-attachments/files/15533400/AH-94.Dragonfly.Manual.pdf)
here is an example pdf

**Comment by fredemmott** [comment]
@Lemonade137 the PDF you attached is corrupted, which is the cause of the crash. Future versions of OpenKneeboard will not crash on it, but it will not be able to display it. It also can't be opened by Chrome, Edge, or Adobe Acrobat.
