### ISSUE TITLE
OKB freezing during mid race

### ISSUE THREAD

**Issue by TexanSin83** [OpenKneeboard/OpenKneeboard#592]
OKB freezing during mid race.  have to Close program, end task in task manager then restart program. 
[OpenKneeboardApp.exe.31144.zip](https://github.com/user-attachments/files/15571831/OpenKneeboardApp.exe.31144.zip)

**Comment by fredemmott** [comment]
The dump you've attached is from a crash of v1.8.2 on June 1st, not the freeze of 1.8.3 you've mentioned on discord - please follow the steps at <https://openkneeboard.com/troubleshooting/crashes-and-freezes.html#getting-a-dump-file-for-a-freeze> and attach the freeze's dump here

Unfortunately, the dump isn't useful for looking at this specific crash either - if you're fine with crashes creating a > 100MB file, load `%PROGRAMFILES%\OpenKneeboard\scripts\enable-full-dumps.reg`, and open a separate issue with that dump for the crash

**Comment by fredemmott** [comment]
Freezes don't usually create dumps; the linked instructions show how to create a dump for a frozen process from task manager.

**Comment by TexanSin83** [comment]
Here is one from today.  I had to do the right click in task manager to dump it

[https://drive.google.com/file/d/1H0ZUqOR0hMV4t8T3TQ6rwCMg2S2ExMcc/view?usp=sharing]((https://drive.google.com/file/d/1H0ZUqOR0hMV4t8T3TQ6rwCMg2S2ExMcc/view?usp=sharing))

**Comment by fredemmott** [comment]
Sorry, as far as that dump shows, everything's working fine :( Could you collect a trace with these instructions?

https://openkneeboard.com/troubleshooting/logs-and-traces.html#standard-traces

**Comment by fredemmott** [comment]
Closing as stale; not enough information to investigate. Will re-open if trace is provided and shows a problem.
