### ISSUE TITLE
Plugins: JS custom actions

### ISSUE THREAD

**Issue by fyyyyy** [OpenKneeboard/OpenKneeboard#594]
Having 10 JsButtons assignable would be very useful. Each web dashboard app can decide on what these do via the javascript api. 

```js
window.OpenKneeboard.jsButton1.on('click',
  (e) => myDashboard.changeZoom()
)
```

This would also allow the web dashboards to add their own JsButton -> action mapping layer, i.e.

```js
window.OpenKneeboard.jsButton1.on('click',
  (e) => myDashboard.inputMapping('button1').action()
)
```

See #240

**Comment by fredemmott** [comment]
These would probably be via `OpenKneeboard.addEventListener("input/customButton1", ...)` or similar

**Comment by fredemmott** [comment]
Retitled as github search wasn't finding this when I searched for 'button' :)

This might tie into #612 , allowing any number of bindable actions, and not requiring that the user use the same hotas button for 'customaction1' on all tab types.

**Comment by fredemmott** [comment]
Tying into #612, will split out another issue for bindings
