### ISSUE TITLE
Feature: Two independent kneeboards for 2D users too

### ISSUE THREAD

**Issue by OR-WS** [OpenKneeboard/OpenKneeboard#598]
Per the title. Can us 2D users get a second kneeboard too? Functions I'm thinking of:

- Separate show/hide, page inc/decr, and tab inr/decr binds per KB.
- Option to slave the show/hide bind so that if either the 1st KB or 2nd KB show/hide bind is used, both KBs are shown/hidden.
- Seperate offset settings (X amount of pixels from the side, Y amount of pixels from the top) per KB.
- Optionally: a set of tabs per KB within a profile.

Use cases will obviously vary but it would be very handy to have an MDC up on one KB with the ability to browse through other EFB pages on the other KB for instance.

**Comment by fredemmott** [comment]
This is multiple existing issues, but primarily https://github.com/OpenKneeboard/OpenKneeboard/issues/155

**Comment by OR-WS** [comment]
> This is multiple existing issues, but primarily #155

Damn, I could vaguely recall ever asking about it but I forgot I raised a request earlier.
