### ISSUE TITLE
Cant open OpenKneeboard-v1.8.3 even after first install

### ISSUE THREAD

**Issue by magellan-99** [OpenKneeboard/OpenKneeboard#601]
Cant open OpenKneeboard-v1.8.3 even after first install，my dump file is in attach, plz help
[OpenKneeboardApp.exe.12856.dmp](https://github.com/user-attachments/files/16036841/OpenKneeboardApp.exe.12856.dmp)

**Comment by fredemmott** [comment]
Unfortunately there's no useful information in that minidump; please try creating a full dump following the steps at <https://openkneeboard.com/troubleshooting/crashes-and-freezes.html#getting-a-dump-file-for-a-crash>

**Comment by magellan-99** [comment]
> Unfortunately there's no useful information in that minidump; please try creating a full dump following the steps at https://openkneeboard.com/troubleshooting/crashes-and-freezes.html#getting-a-dump-file-for-a-crash
I had send a onedrive share link to openkneeboard-dumps@fred.fredemmott.com, plz check

**Comment by magellan-99** [comment]
> Unfortunately there's no useful information in that minidump; please try creating a full dump following the steps at https://openkneeboard.com/troubleshooting/crashes-and-freezes.html#getting-a-dump-file-for-a-crash

I had send a onedrive share link to [openkneeboard-dumps@fred.fredemmott.com](mailto:openkneeboard-dumps@fred.fredemmott.com), plz check

**Comment by magellan-99** [comment]
Add a google driver link: https://drive.google.com/drive/folders/1wA0brNmg6mqkoA614aPoZ_Htlzns2-OY?usp=sharing

**Comment by fredemmott** [comment]
Are you able to open `C:\Program Files\OpenKneeboard\bin\Quick Start.pdf` in another PDF viewer?

**Comment by magellan-99** [comment]
Yes, I can open this pdf in edge

**Comment by fredemmott** [comment]
Can you give the msi at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/9725736784 a try, and:
- if it starts (a) does the quick start guide load? (b) either way, please [attach logs](https://go.openkneeboard.com/logs)
- if not:
  1. load `c:\program files\OpenKneeboard\scripts\enable-log-files.reg` ; say yes when prompted for administrator access
  2. run openkneeboard again
  3. attach a zip of `Saved Games\OpenKneeboard\logs` here

**Comment by magellan-99** [comment]
I reinstalled the Windows10 system and the problem was resolved...

**Comment by fredemmott** [comment]
Glad to hear it; hopefully the original issue has been resolved for the next major update, but as it's now fixed for you, unable to investigate further.
