### ISSUE TITLE
OpenKneeboard can‘t go into VR mode

### ISSUE THREAD

**Issue by magellan-99** [OpenKneeboard/OpenKneeboard#603]
![untitle1](https://github.com/OpenKneeboard/OpenKneeboard/assets/41447919/5194a7d9-592b-4f93-aee5-7138480e2332)
![untitle2](https://github.com/OpenKneeboard/OpenKneeboard/assets/41447919/43e93a62-b2e6-47ab-8a31-6b6b042993be)
As shown in the attached picture, I set up the SteamVR Rendering API in OpenKneeboard, but when I enter the VTOL VR game through SteamVR, OpenKneeboard-viewer tells me that its output is always in Non-VR state. How should I solve this problem? In addition, I want to say, if it is not in VR state, who would want to use such a software to view reference information? Isn't it better to print it out directly?

**Comment by fredemmott** [comment]
ignore what the optional viewer app says; the viewer app is for testing and streamers, and is just saying that the viewer app itself is showing the non-vr view, not a mirror of the vr view.

If you actually have a problem in game and https://openkneeboard.com/troubleshooting/steamvr-or-openxr.html doesn’t help, attach logs: https://openkneeboard.com/troubleshooting/logs-and-traces.html

**Comment by magellan-99** [comment]
> 忽略可选查看器应用程序的内容；查看器应用程序用于测试和流媒体，只是说查看器应用程序本身显示的是非虚拟现实视图，而不是虚拟现实视图的镜像。
> 
> 如果您在游戏中确实遇到问题并且https://openkneeboard.com/troubleshooting/steamvr-or-openxr.html没有帮助，请附加日志：https://openkneeboard.com/troubleshooting/logs-and-traces.html

Solved the problem with this tip: Reset OpenKneeboard’s VR settings to defaults. By the way, selecting this will cause the program to freeze and require a restart.thanks!
