### ISSUE TITLE
"glitching" and unable to write

### ISSUE THREAD

**Issue by heli66** [OpenKneeboard/OpenKneeboard#606]
it keeps glitching a little and wont let my wright on it in game dcs 
[OpenKneeboard-v1.8.3.2118-2024-07-04-10-52.zip](https://github.com/user-attachments/files/16102458/OpenKneeboard-v1.8.3.2118-2024-07-04-10-52.zip)

**Comment by fredemmott** [comment]
What have you tried from the troubleshooting guide? And what does “glitching a little” mean?

**Comment by fredemmott** [comment]
Follow the steps at the top of <https://openkneeboard.com/troubleshooting/logs-and-traces.html#saving-debug-logs> before saving your logs. Your logs only include OpenKneeboard starting, nothing else.

Additionally, which model/make of tablet are you using, with which driver?

**Comment by heli66** [comment]
ow I'm not you sing any tablet was with mouse

**Comment by fredemmott** [comment]
https://openkneeboard.com/faq.html#how-do-i-use-the-mouse-in-game
