### ISSUE TITLE
Add a "clear notes" button to clear pages from tablet-input data

### ISSUE THREAD

**Issue by AndLindemann** [OpenKneeboard/OpenKneeboard#61]
When writing with a (Wacom or other) tablet on a tab, it'd be cool to have access to an "erase all" button (a keybinding would be good enough here for me), that just erases all of the tablet notes from the tab.
While it can be done with the erase functionality of the pens, depending on the amount of notes that's going to be a lot of wiping around on the page to clear it up between flights or just when the page is full and you want to throw it all away to start clean.

**Comment by patrikman** [comment]
Yes, with that feature I could just add a notes folder and a blank page (or
other template). Then hit ‘duplicate’ whenever I needed more space. 👍

**Comment by fredemmott** [comment]
blocked on #116
