### ISSUE TITLE
OpenKneeboard is looking for the wrong F-5E folder

### ISSUE THREAD

**Issue by NidhoggAC** [OpenKneeboard/OpenKneeboard#610]
Is looking for a folder called "F-5E-3".  However the module installs in a folder called 'F-5E'.

I adding the following to the mapping in "DCS-Aircraft-Mapping.json".

`"F-5E-3": "F-5E"`

But aircraft page still can't loaded for F-5E. The F-5E built-in kneeboard looks is custom Lua files, which are not supported.

![image](https://github.com/OpenKneeboard/OpenKneeboard/assets/172209013/53d0aef5-8bdd-4f37-9f23-b7be881ddece)

**Comment by fredemmott** [comment]
Thanks, fixed for the next version of OpenKneeboard
