### ISSUE TITLE
Zoom depending on the longer edge of the page

### ISSUE THREAD

**Issue by rafgaj** [OpenKneeboard/OpenKneeboard#620]
My issue is that the zoom for vertical and horizontal pages is always scaled by width. Then, the horizontal pages are much smaller. Is it possible for the zoom to be scaled, e.g. by the longer edge?

**Comment by fredemmott** [comment]
Zoom is always just a multiplication of both parts by the same value. can you clarify what you mean?

**Comment by fredemmott** [comment]
If this isn't related to the zoom feature and just how big things are in openkneeboard generally, if you want landscape documents to be wider, adjust the 'max width' setting in settings -> VR

**Comment by rafgaj** [comment]
Here is how I see right now vertical and horizontal pages:

![image](https://github.com/user-attachments/assets/9b6b02cf-2966-4b3b-b854-791a0f52fa78)
or at least I can't set it differently.

Here's the option I'm asking about:

![image](https://github.com/user-attachments/assets/9305394d-f10c-46cf-8864-d91f8aecce69)
In general, my proposal applies to normal and zoom views.

**Comment by rafgaj** [comment]
Fred, yes, 'max width' setting in settings -> VR fixed my issue, thx.
