### ISSUE TITLE
Add the possibility to save different presets/profiles

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#63]
As a feature request, it should be possible to set up the kneeboard in different presets and save these. Best to start with a dedicated link. Goal should be to set up OpenKneeboard for different sim's and in the sim for different planes and save position, content, behavior etc. in an own profile which could be open via a link on the desktop or such like.

**Comment by fredemmott** [comment]
More likely to do this as a 'nested' configuration rather than entirely separate configurations; for example:

- common settings, such as bindings
- game settings
- aircraft settings

Anything in common settings (including bindings) can be overridden by game settings, anything in game settings can be overridden by aircraft settings

**Comment by fredemmott** [comment]
For a dedicated link as a workaround, a .bat or .ps1 script can be used in combination with the remote 'launcher' executable; you'd want to shuffle around the Settings.json in Saved Games\OpenKneeboard

**Comment by fredemmott** [comment]
My ideal would be to have a switcher button in the title bar like the 'Hello' button here, however Microsoft's WinUI3 framework currently does not support clickable content in the title bar:

![image](https://user-images.githubusercontent.com/360927/193460176-0a33cdd7-c7c9-4f3f-a166-b368ff3a118a.png)

The Windows App SDK could be used directly, but that only supports this on Windows 11

**Comment by fredemmott** [comment]
Going with this for now:

![image](https://user-images.githubusercontent.com/360927/193463140-e81e8ae9-8e28-4e90-86c5-192b1f55e2c1.png)

**Comment by fredemmott** [comment]
This should be in v1.3, but must be enabled in 'advanced settings'

![image](https://user-images.githubusercontent.com/360927/193466783-dbb066f1-8b5a-4a42-b746-a8d142dd0097.png)

**Comment by fredemmott** [comment]
v1.3-beta4 adds a 'SET_PROFILE' exe for use with streamdeck/huion/voice attack
