### ISSUE TITLE
Bookmark/organize pages within a tab

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#64]
The ability to organize the pages and tabs somehow like VRK.

The feature should be working "Pre-planed" during setup in the main window, and being able to add pages on the fly during a mission. In the first case, the renaming should be possible.

As an example:

![unknown](https://user-images.githubusercontent.com/103137203/163182463-7f482e1f-4622-4aaf-bad2-fa11187439ba.png)

**Comment by fredemmott** [comment]
OpenKneeboard's model is:
- a page is literally 1 page; a 3-page PDF becomes 3 pages in OpenKneeboard, a folder with 5 images becomes 5 pages
- a tab is a collection of pages that are grouped together, such as a folder, single PDF, or mission

I think there's multiple requests here, and I'm not certain how they should be split up - could you clarify? I think theres:
- [ ] add support for bookmarks within a 'tab'
- [ ] possible alternative: ability to split a tab into multiple tabs
- [ ] add ability to add a new blank page
- [ ] add ability to add a new page from a template (e.g. a form)
- [x] (already exists - settings -> tabs) add ability to add content from files/folders before flying

**Comment by fredemmott** [comment]
> add support for bookmarks within a 'tab'
> possible alternative: ability to split a tab into multiple tabs

The difference between these two would be if you are on the last page of one tab, do you expect 'next page' to take you to the first page of the next group of pages?

If it were a 'bookmarks' model, it definitely should, but if it were 'split tabs', it probably shouldn't, or should depend on a broader setting: there's separately been a couple of requests for 'next page' to take you back to the first page of the current group of pages

**Comment by LtJaeger** [comment]
I try it in different words, but since English isn't my native language, there might be some misunderstandings on my side.

Referencing the provided picture:

The top row "bookmarks" would represent openkneeboard tabs, the side "bookmarks" the pages.
Currently, I have to navigate through the tabs via key press to get to the needed one. In the VRK example, I would just click via pen on the relevant tab, and I'm with the wanted document. These document might consist of a couple of pages (like left side Jester Tab) which, for the sake of easy navigation, I amended with markers to relevant pages. In this case it is a pdf (copied out of the manual), so there is no register and I have to step thru all the pages to reach the desired one. 

I would wish for a "bookmark" feature which allows me (staying with the Jester example) to reach with (in this case) just two clicks the desired section in a document.

These "bookmarks" could be done pre planed (in the desktop app) and be named, or on the fly with just a generic reference (e.g. #1 , #2, ...)

**Comment by fredemmott** [comment]
#116 will need doing first; #29 and #65 are already filling up the toolbar, and #116 is needed from a code perspective to make adding additional areas or pop-outs practical

**Comment by fredemmott** [comment]
#116 is done which:
- opens the possibility of a left-nav in-game
- also made it practical to add pop-out menus, where this could easily fit, e.g.:

![image](https://user-images.githubusercontent.com/360927/210118760-6b36b726-f95d-4904-991c-e785c870bdae.png)

This would now be very straightforward to implement

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/213959051-626bae10-c051-4f9b-95e3-6bd98905af20.png)

**Comment by LtJaeger** [comment]
Wow

**Comment by fredemmott** [comment]
- [ ] support renaming bookmarks
- [ ] remove blue hover highlight if the other kneeboard becomes inactive

**Comment by fredemmott** [comment]
I've split out saving/restoring bookmarks as #251 needs doing first and is pretty complex by itself
