### ISSUE TITLE
Add the ability to navigate pages/tabs with the pen

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#65]
Currently, the navigation using a tablet (huion) has to be done with the provided control exe files and the press of a button. 

Especially in VR, it seems easier to have the possibility to navigate pages, tabs etc. via pen. Reference to VRK, but with way smaller buttons.

**Comment by fredemmott** [comment]
That now fully duplicates the out-of-app toolbar; this adds page navigation, but not yet tabs.
