### ISSUE TITLE
v1.9.6: crash moving mouse cursor over app window when profile has no tabs or tabs aren't loaded yet

### ISSUE THREAD

**Issue by Feukair** [OpenKneeboard/OpenKneeboard#663]
Just upgraded to 1.9.6 and consistently getting a crash whenever changing profiles. 

Will send crash dump via email.

**Comment by fredemmott** [comment]
When it crashed, it should have shown a .txt and a different dump file, in `%LOCALAPPDATA%\OpenKneeboard\Logs\Crashes` - could you share those, and the `%LOCALAPPDATA%\OpenKneeboard\Settings` folder too please?

**Comment by fredemmott** [comment]
Or better, instead of the settings zip, the debug logs zip : https://go.openkneeboard.com/logs

**Comment by Feukair** [comment]
I don't have the other txt and dump file from the same timestamp. But here is one of the same type from a few minutes before. 
    On Thursday, September 12, 2024 at 09:38:51 PM EDT, Fred Emmott ***@***.***> wrote:  
 
 


Or better, instead of the settings zip, the debug logs zip : https://go.openkneeboard.com/logs

**Comment by Feukair** [comment]
Here's my settings folder. There's some very old files in there from a couple years back. 

    On Friday, September 13, 2024 at 05:14:45 AM EDT, Larry Touchette ***@***.***> wrote:  
 
  I don't have the other txt and dump file from the same timestamp. But here is one of the same type from a few minutes before. 
    On Thursday, September 12, 2024 at 09:38:51 PM EDT, Fred Emmott ***@***.***> wrote:  
 
 


Or better, instead of the settings zip, the debug logs zip : https://go.openkneeboard.com/logs

**Comment by Feukair** [comment]
I also had two more crashes last night that dumped larger files. I think they happened while switching profiles too, but they may have happened while I was changing settings like adding a screen capture window or changing settings in a screen capture tab. 
OpenKneeboardApp-crash-20240913T010128-38564.zip


| 
| 
|  | 
OpenKneeboardApp-crash-20240913T010128-38564.zip


 |

 |

 |



OpenKneeboardApp-crash-20240913T010211-29292.zip


| 
| 
|  | 
OpenKneeboardApp-crash-20240913T010211-29292.zip


 |

 |

 |








    On Friday, September 13, 2024 at 05:18:29 AM EDT, Larry Touchette ***@***.***> wrote:  
 
  Here's my settings folder. There's some very old files in there from a couple years back. 

    On Friday, September 13, 2024 at 05:14:45 AM EDT, Larry Touchette ***@***.***> wrote:  
 
  I don't have the other txt and dump file from the same timestamp. But here is one of the same type from a few minutes before. 
    On Thursday, September 12, 2024 at 09:38:51 PM EDT, Fred Emmott ***@***.***> wrote:  
 
 


Or better, instead of the settings zip, the debug logs zip : https://go.openkneeboard.com/logs

**Comment by Feukair** [comment]
Thank you for making this awesome utility. The best VR gaming add-on for sims IMO.
    On Friday, September 13, 2024 at 05:23:18 AM EDT, Larry Touchette ***@***.***> wrote:  
 
  I also had two more crashes last night that dumped larger files. I think they happened while switching profiles too, but they may have happened while I was changing settings like adding a screen capture window or changing settings in a screen capture tab. 
OpenKneeboardApp-crash-20240913T010128-38564.zip


| 
| 
|  | 
OpenKneeboardApp-crash-20240913T010128-38564.zip


 |

 |

 |



OpenKneeboardApp-crash-20240913T010211-29292.zip


| 
| 
|  | 
OpenKneeboardApp-crash-20240913T010211-29292.zip


 |

 |

 |








    On Friday, September 13, 2024 at 05:18:29 AM EDT, Larry Touchette ***@***.***> wrote:  
 
  Here's my settings folder. There's some very old files in there from a couple years back. 

    On Friday, September 13, 2024 at 05:14:45 AM EDT, Larry Touchette ***@***.***> wrote:  
 
  I don't have the other txt and dump file from the same timestamp. But here is one of the same type from a few minutes before. 
    On Thursday, September 12, 2024 at 09:38:51 PM EDT, Fred Emmott ***@***.***> wrote:  
 
 


Or better, instead of the settings zip, the debug logs zip : https://go.openkneeboard.com/logs

**Comment by fredemmott** [comment]
There don't appear to be any additioanl files, either on github, or on the emails you cc'ed to my old email address, but there's some info in the first dump that I can work with.

**Comment by fredemmott** [comment]
The issue from the original dump is fixed; there should be an MSI available at <https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/10849945885> in ~ 40 minutes

If you still have issues with that (or the most recent prerelease if there is a version newer than 1.9.6 when you try), please open a new issue including:
- the crash dump and log file from the crashes directory
- the debug logs zip created from the help page in the app; I know you can't do this *after* the crash, but doing it on a fresh start is still helpful

**Comment by Feukair** [comment]
Hi Fred. I tried that build. Launched it, tried to select different profile, and immediately got a crash dump. I will email you a google drive link to the dump.

**Comment by fredemmott** [comment]
Reopening as I'm guessing you accidentally closed this.

Might be fixed in https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/10903874103 (again ~ 40 minutes)

Looks like the reason you're encountering problems that I'm not is that your profiles contain very large PDFs, and you're switching profiles before the PDFs have fully loaded. It's a bug that that doesn't work fine, but I'll do some more testing with large PDFs.

**Comment by fredemmott** [comment]
Ah no, I closed this as the original issue was fixed and this is an unrelated issue.
