### ISSUE TITLE
v1.8 can't read settings from v1.9

### ISSUE THREAD

**Issue by fr3nchy74** [OpenKneeboard/OpenKneeboard#664]
After un-installing 1.9.6 and re-installing 1.8.10 and copying my settings over the one that are created automatically by OpenKneeboard, launching it will result into a crash 100% of the time. Dump is too large to be attached, but here's my settings:
[Settings.zip](https://github.com/user-attachments/files/17004336/Settings.zip)

**Comment by fredemmott** [comment]
That settings zip is from v1.9, not v1.8; earlier openkneeboard versions are not able to understand settings from later versions. If you did not make a backup of your v1.8 settings, there should be one in `%LOCALAPPDATA%\OpenKneeboard\Backups` (the oldest one)

**Comment by fredemmott** [comment]
With a v1.8 settings folder, the subfolders of `Profiles` have readable names rather than random IDs.

If you do not have a v1.8 settings backup, then your options are either to start from scratch, or we figure out why things are crashing for you on v1.9

**Comment by fr3nchy74** [comment]
Ok, so i assume you do not want the dump file for 1.8.10 with 1.9 settings.

**Comment by fredemmott** [comment]
Is/was there nothing in %LOCALAPPDATA%\OpenKneeboard\Backups ? The first run of v1.9.2 should have created one at app startup, well before it got to the first issue you encountered.

Thanks, but no - the dumps are for diagnosing issues, but this is diagnosed.

**Comment by fr3nchy74** [comment]
I fished the folder from the Trash, the backup is there

**Comment by fredemmott** [comment]
The backups feature is new; if you don't mind, could you share why the backups were in your trash?

So far, everyone who's wanted to downgrade deleted the backups first; is there anything you can think that I could have done (e.g. where I put them) that would have led to you keeping them?

**Comment by fr3nchy74** [comment]
Yeah I deleted the folder

**Comment by fredemmott** [comment]
Did you delete the backups folder specifically, or was it part of deleting all of `%LOCALAPPDATA%\OpenKneeboard`?

if they had been, for example, in `%LOCALAPPDATA%\OpenKneeboard Backups`, does it feel likely you would have kept them?

**Comment by fr3nchy74** [comment]
I deleted the whole folder
