### ISSUE TITLE
v1.9.7.2368: Freezing/Crashing on Profile Switch

### ISSUE THREAD

**Issue by guywholikestobreakthings** [OpenKneeboard/OpenKneeboard#665]
On profile switch, Openkneeboard freezes, and then crashes.  On previously publicly released dev build, if I switched profiles it would freeze, but if I minimized the window, then refocused it, the profile would be switched.  On the latest nightlybuild link it crashes completely on profile switch.   
[OpenKneeboardApp.exe(1).2248.zip](https://github.com/user-attachments/files/17006572/OpenKneeboardApp.exe.1.2248.zip)

**Comment by fredemmott** [comment]
- Did it create a crash/log in `%LOCALAPPDATA%\OpenKneeboard\Logs\Crashes`? If so, can you attach those too
- Can you attach the debug zip?

**Comment by guywholikestobreakthings** [comment]
[OpenKneeboardApp-crash-20240902T174728-20140.dmp](https://github.com/user-attachments/files/17006605/OpenKneeboardApp-crash-20240902T174728-20
[OpenKneeboardApp.exe(1).14756.zip](https://github.com/user-attachments/files/17006616/OpenKneeboardApp.exe.1.14756.zip)
140.dmp)
[OpenKneeboardApp.exe.2248
[OpenKneeboardApp.exe.14756.zip](https://github.com/user-attachments/files/17006619/OpenKneeboardApp.exe.14756.zip)
.zip](https://github.com/user-attachments/files/17006617/OpenKneeboardApp.exe.2248.zip)

**Comment by guywholikestobreakthings** [comment]
Hopefully that's what was needed.

**Comment by fredemmott** [comment]
For the debug zip, before the crash, <https://openkneeboard.com/troubleshooting/logs-and-traces.html#saving-debug-logs>

It would also be useful if you could share the steps here: https://openkneeboard.com/troubleshooting/logs-and-traces.html#standard-traces

**Comment by fredemmott** [comment]
> OpenKneeboardApp-crash-20240902T174728-20140.dmp

You don't appear to have actually uploaded this file - it's not available. Both it, and the corresponding .txt file would be useful

**Comment by guywholikestobreakthings** [comment]
[OpenKneeboardApp-crash-20240915T163940-14072.dmp](https://github.com/user-attachments/files/17006652/OpenKneeboardApp-crash-20240915T163940-14072.dmp)
[OpenKneeboardApp-crash-20240915T163940-14072.txt](https://github.com/user-attachments/files/17006653/OpenKneeboardApp-crash-20240915T163940-14072.txt)

**Comment by guywholikestobreakthings** [comment]
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: Stopping frame loop...
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: Exiting DirectInputListener::Run() for WINWING Orion Throttle Base II + F18 HANDLE, with 0 uncaught exceptions
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: Removing instance data...
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: Releasing kneeboard resources tied to hwnd
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: Removing window subclass
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: Stopping frame loop...
[2024-09-15 12:39:40 OpenKneeboardApp.exe (14072)] OpenKneeboard-WinUI3: 💀 FATAL: Assertion failed (mPromise): Can't await a task that has been moved or already awaited @ :0:0 - OpenKneeboardApp+0xF9F95

**Comment by fredemmott** [comment]
Unfortunately that's a separate issu e- it's when closing the app, not when the swiching profiles

**Comment by fredemmott** [comment]
> For the debug zip, before the crash, https://openkneeboard.com/troubleshooting/logs-and-traces.html#saving-debug-logs
> 
> It would also be useful if you could follow the steps here: https://openkneeboard.com/troubleshooting/logs-and-traces.html#standard-traces

bumping this :)

**Comment by guywholikestobreakthings** [comment]
Here's the trace
[trace.zip](https://github.com/user-attachments/files/17006965/trace.zip)

**Comment by guywholikestobreakthings** [comment]
[OpenKneeboard-v1.9.7.2368-20240915T1439.zip](https://github.com/user-attachments/files/17006994/OpenKneeboard-v1.9.7.2368-20240915T1439.zip)

**Comment by fredemmott** [comment]
Thanks; most of the dumps you've shared are for another issue: if you logout of windows or shutdown your computer within a fraction of a second of strating OpenKneeboard, it doesn't handle it well.

As for issues when changing profiles, there should be an MSI at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/10873669162 in ~ 40 minutes or so ; could you try that?

It might fix it - otherwise, another trace, and the dump+txt (if there is a new one) would be useful - thanks!

**Comment by fredemmott** [comment]
If you're still encountering issues, please try with the latest prerelease instead, which is currently https://github.com/OpenKneeboard/OpenKneeboard/releases/tag/v1.9.8

**Comment by fredemmott** [comment]
Closing - all issues reported in this thread have been fixed. If you encounter additional problems, please open a new issue.
