### ISSUE TITLE
Add a basic calculator

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#67]
A basic calculator should be implemented via an pre-set tab.

**Comment by fredemmott** [comment]
related but not the same thing: #17

**Comment by jonasrembratt** [comment]
This would be great!

**Comment by fredemmott** [comment]
I was hoping that #94 would provide a workaround for this, but no. While it's now possible to show the windows calculator inside an OpenKneeboard Beta, I've not found a way to inject mouse events to it (or other UWP apps) when it's not the foreground window.

**Comment by fredemmott** [comment]
This is available as a plugin for the *next* version of OpenKneeboard: https://github.com/OpenKneeboard/Calculator-Plugin
