### ISSUE TITLE
Pen "click" input on web UI (via Windows capture), hangs the browser

### ISSUE THREAD

**Issue by fr3nchy74** [OpenKneeboard/OpenKneeboard#679]
Every time I use the pen (drawing tablet) with DCS Web Editor's export of F10 and "click" on the UI, the browser hangs. 100% of the time. I can click on the map itself and it will move the map, but using any of the UI is not possible.

I tried with Edge and Chrome, same result on both.

**Comment by fredemmott** [comment]
Sorry, mouse forwarding is “it works or it doesn’t”.

https://openkneeboard.com/troubleshooting/window-capture-compatibility/#mousetablet-forwarding

**Comment by fr3nchy74** [comment]
Bummer :( ... It kind of works as I can drag the map around
