### ISSUE TITLE
Add the display of Mission time

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#68]
Add the display of real world time and (for me more important) the mission time imported from the sim (DCS)

**Comment by Hanzee94** [comment]
Yep, real time would be nice. Sometimes I need to keep real time in check and this would be an easy way to check it without pulling the headset off.

**Comment by fredemmott** [comment]
Thanks, retitled given #15

**Comment by fredemmott** [comment]
Going to call this done, despite not having zulu time, as zulu time seems bugged in DCS right now - reported to E.D.

1. create a mission in NTTR starting today at 00:00:00
2. check briefing says starts at 00:00:00 (midnight). Clearly midnight local time when looking outside cockpit
3. check cockpit clock and CDU GPS GMT time, says 20:00:00 (8pm), should be 08:00:00 (8am), as nevada is UTC-8
4. repeat for 12:00 (midday). Clearly midday local time when looking outside cockpit.
5. cockpit clock and CDU GPS GMT time says 08:00:00 (8am), should be 20:00:00

**Comment by fredemmott** [comment]
Nope... started in NTTR, but mission editor flipped to caucasus at some point
