### ISSUE TITLE
Feature Request: Non-VR Absolute Positioning

### ISSUE THREAD

**Issue by ajmilner85** [OpenKneeboard/OpenKneeboard#686]
The current method of setting the kneeboard's position for non-vr can be frustrating to work with, particularly in setups with multiple monitors and auxiliary displays for MFDs, RWR etc. It would be great to have an option to specify the x and y coordinates of the kneeboard origin directly, or an x and y offset in pixels from the Left/Center/Right positions instead of just the single padding value for both.

**Comment by fredemmott** [comment]
Duplicate (subset) of #258
