### ISSUE TITLE
kneeboard crash with iOverlay

### ISSUE THREAD

**Issue by dynamicat** [OpenKneeboard/OpenKneeboard#692]
I have provided the crash dump, the application opens for 3 seconds and closes again.  I tried reinstall and renaming the folder in %appdata%
[OpenKneeboardApp.exe.4680.dmp](https://github.com/user-attachments/files/17943702/OpenKneeboardApp.exe.4680.dmp)

![image](https://github.com/user-attachments/assets/73467d87-b12d-4d4b-81fe-91c95d163678)

**Comment by fredemmott** [comment]
- This looks like it might already be fixed for the next version; can you try with the msi at the bottom of https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/11917634383 ?
- You're currently on v1.8; for v1.8, the settings are in saved games, not %appdata%; in v1.9+ they're in %localappdata%

**Comment by dynamicat** [comment]
[OpenKneeboardApp.exe.27596.dmp](https://github.com/user-attachments/files/17951817/OpenKneeboardApp.exe.27596.dmp)
doesnt look like its fixed it.  Takes me straight the crash dump folder.  I have attached the .dmp

**Comment by dynamicat** [comment]
fixed i renamed the setting folder
