### ISSUE TITLE
OpenKneeboard Crashing with error : OpenKneeboard-WinUI3: 💀 FATAL: Failed to enqueue coroutine resumption for the desired thread: 0x80010105

### ISSUE THREAD

**Issue by hellion102** [OpenKneeboard/OpenKneeboard#703]
Hello.

When I attempt to change to a different profile OpenKneeboard crashes using version : OpenKneeboard v1.9.12+gha.2485

I see this error in the debug log:
OpenKneeboard-WinUI3: 💀 FATAL: Failed to enqueue coroutine resumption for the desired thread: 0x80010105

Attached dmp files.
[OpenKneeboardApp-crash-20241213T030608-7344.dmp](https://github.com/user-attachments/files/18120493/OpenKneeboardApp-crash-20241213T030608-7344.dmp)
[OpenKneeboardApp-crash-20241213T030608-7344.txt](https://github.com/user-attachments/files/18120495/OpenKneeboardApp-crash-20241213T030608-7344.txt)

Should I revert to an earlier version?
If so, what would be the safest way to do that to not lose any changes?

Thanks!

**Comment by fredemmott** [comment]
Thanks for the dump files :)

> Should I revert to an earlier version?

Up to you. If this is getting in the way of you using it and you want to use it, probably yes ;)

> If so, what would be the safest way to do that to not lose any changes?

The only way to revert is to uninstall the new version, and then install the old version.


For v1.9, there are backups of old settings files in `%LOCALAPPDATA%\OpenKneeboard Backups` - you can restore an older version - see https://openkneeboard.com/faq/#where-are-openkneeboards-settings-saved

You can not directly use the settings from one OpenKneeboard version in an older version, unless they're in the same `v1.x` series - e.g. v1.8.0 can open v1.8.12's settings, but v1.8 can't open v1.9's and v1.7 can't open v1.8's.

**Comment by fredemmott** [comment]
Do you have the same issue when not running as administrator? The info shows that you've clicked through this:

![image](https://github.com/user-attachments/assets/f73f18e0-fbd1-4816-ae83-c0ae449fd56f)

**Comment by fredemmott** [comment]
hmm, though it's possible that it crashed after attempting to show that, but before it became visible

**Comment by hellion102** [comment]
Hell Emmott.

Correct, I run Open Kneeboard in administrator mode because it's crashing when it's attempting to load the first profile when not running in adminstrator mode.

Also, I use OpenKneeboard for the DCS flight simming and the VR kneeboard does show up in the game. Not sure why, but when I run DCS first and then run Open Kneeboard in administrator mode after (while DCS is staring up), it ends up working every time.
I am using the Pimax OpenXR and have tried changing the layer ordering with the "OpenXR-API-Layers-GUI" tool to no avail.

With the latest OpenKneeboard changes I upgraded to a while back,  every time I change to a new profile, it crashes when loading the profile.
It's annoying since I then also have to restart DCS sim every time.

VR is a pain when you have to keep taking it on and off for correcting issues.

I wonder since I have your attention, is a keyboard shortcut available for changing to different profiles?
You have a lot of keyboard shortcuts, but not that one would be great since DCS does not allow you to view the desktop to cycle the profiles in Openkneeboard.
I would then map that if existed to Voice Attack to do it without having to take the VR headset off.
That would be awesome!

Thanks,
Rob.
🙂


________________________________

**Comment by fredemmott** [comment]
You might want to try the v1.9 prerelease as non administrator - several issues switching profiles are fixed there.

if you have any issues with non administrator on v1.9, please attach crash dumps and logs from them to a ticket per issue.

sorry, I do not look into any issues that occur when running as administrator - running as administrator is explicitly unsupported.

**Comment by fredemmott** [comment]
Thanks for filing #705 - I think this issue is addressed by my previous comment, #705, and ties into #704

**Comment by fredemmott** [comment]
> Did you mean that I should uninstall version 1.9.12 and then install 1.9 instead and run in non-admin mode?
If so, will try that.

No, just to try the latest v1.9.anything as not-adminsitrator, and you've done that in in #705

> Also, did you get my note about supporting switching (or cycling) profiles by keyboard shortcuts?
Is that planned to be implemented hopefully?

Ah, I missed that as it was not related to the topiic of that issue.

https://openkneeboard.com/faq/feature-requests/ - but also see https://openkneeboard.com/features/remote-controls/
