### ISSUE TITLE
v1.8 crashing on startup with invalid web dashboard URL

### ISSUE THREAD

**Issue by goffemannen** [OpenKneeboard/OpenKneeboard#708]
I have tried to re-install and nothing works. It just crashes on startup.

It crashed the first time after I was adding a new tab I think. I accidentally typed just normal text instead of a browser link. 

[OpenKneeboardApp.exe.9608.zip](https://github.com/user-attachments/files/18203113/OpenKneeboardApp.exe.9608.zip)

**Comment by goffemannen** [comment]
It says this on the troubleshooting site but that settings folder does not exist for me.

v1.9 and above: Settings are now in %LOCALAPPDATA%\OpenKneeboard\Settings, not Saved Games\OpenKneeboard.

This is what I find there. 
![image](https://github.com/user-attachments/assets/dd2ddc9b-8627-4a70-bc57-71fd1adf19f2)

**Comment by fredemmott** [comment]
You've got v1.8 (stable) installed, not v1.9 (testing) - you want the saved games path.

**Comment by fredemmott** [comment]
I'm unable to reproduce this on v1.8 or v1.9, and unfortunately the dump isn't useful ; could you try v1.9 (from https://github.com/OpenKneeboard/OpenKneeboard/releases) and:

- see if it's fixed
- if not, share the dump file and txt it produces? v1.9 should produce more useful dump files

**Comment by goffemannen** [comment]
> I'm unable to reproduce this on v1.8 or v1.9, and unfortunately the dump isn't useful ; could you try v1.9 (from https://github.com/OpenKneeboard/OpenKneeboard/releases) and:
> 
> * see if it's fixed
> * if not, share the dump file and txt it produces? v1.9 should produce more useful dump files

That worked..thanks.
