### ISSUE TITLE
Suggestion: Adding profiles based on another profile besides default

### ISSUE THREAD

**Issue by otherguy485** [OpenKneeboard/OpenKneeboard#709]
I would like the ability to chose which existing profile to use as the template when adding a new profile.

Right now I have profiles for several cars and some of them are very similar to each other with minor tweaks.
when I create a new profile it uses the default which requires more editing/moving than if I were able to select something already created that is closer to what I want.

**Comment by fredemmott** [comment]
Duplicate of #537
