### ISSUE TITLE
Built-in aircraft-specific kneeboards aren't loaded (e.g. F14)

### ISSUE THREAD

**Issue by LtJaeger** [OpenKneeboard/OpenKneeboard#78]
The Mission Briefing won't load for me, neither SP nor MP.

Same would be true for the Aircraft Briefing. This would be for the F-14 Tomcat which I fly exclusively. I know that the Aircraft Kneeboard consists of LUA stuff, so not sure if that is already implemented yet, or even possible.

Area briefing works, at least offline I checked.

**Comment by fredemmott** [comment]
> Mission Briefing

Is this the thing that shows up in escape -> briefing, or mission-specific kneeboard pages?

If it's the first, it's not implemented yet - https://github.com/fredemmott/OpenKneeboard/issues/20  - if it's images, can you share a .miz file?

**Comment by LtJaeger** [comment]
Actually it is both

Escape - Mission briefing - OK, not implemented

Mission specific kneeboard - Doesn't show up either
[MISSION PLANNING TEMPLATE V.1.0.4.zip](https://github.com/fredemmott/OpenKneeboard/files/8550117/MISSION.PLANNING.TEMPLATE.V.1.0.4.zip)
(This is our basic bread and butter template)

Plane specific  (F-14) - Doesn't show up (which will be mostly due to LUA stuff, I guess)

Offline the Theater briefing is shown

**Comment by fredemmott** [comment]
When I open that mission in DCS, it works fine for me; I'm just doing DCS -> Mission -> finding that in my downloads, then I get this:

![image](https://user-images.githubusercontent.com/360927/164994346-210e70cb-9f07-4929-8b9b-a025b1903c15.png)

Is something else happening for you?

F-14: is this kneeboard stuff built in to DCS, or something custom? There is no support for lua kneeboards, but if there are images, they should work

**Comment by LtJaeger** [comment]
For the Aircraft kneeboard (F-14)

This is the folder content, so it is a mix of .lua, which I understand is not implemented, and pics. 

![grafik](https://user-images.githubusercontent.com/103137203/165025329-3d9b3fa8-d43d-478b-919a-4c906d95c578.png)

The rest I will check and come back to you. Server currently down for maintenance

**Comment by fredemmott** [comment]
Leaving the mission/lua in general for #20 

Built-in aircraft kneeboard images aren't supported at all, though should be relatively easy to support - though it's a little strange they're under `pages` rather than `images`
