### ISSUE TITLE
POV switches are not recognized

### ISSUE THREAD

**Issue by PickRelated** [OpenKneeboard/OpenKneeboard#80]
I rely heavily on consistency through my key bindings in all planes.

But unfortunately 8-way POV hat switches are not being recognized when binding keys. All other buttons work just fine.

Is there a chance it can be fixed easily?

Thanks for this amaizing tool!

**Comment by fredemmott** [comment]
Relatively straightforward; essentially DirectInput does not consider them to be buttons: each hat is reported as a single number, with centidegrees from north (e.g. 0 for north, 18000 for south), with -1 for center, not as a button per direction. Special handling is needed, but it's relatively straightforward.

**Comment by OR-WS** [comment]
> I rely heavily on consistency through my key bindings in all planes.
> 
> But unfortunately 8-way POV hat switches are not being recognized when binding keys. All other buttons work just fine.
> 
> Is there a chance it can be fixed easily?
> 
> Thanks for this amaizing tool!

Same here! Would very much welcome the additional flexibility to map any type of discrete knob, switch, button, etc.

**Comment by fredemmott** [comment]
Things that DirectInput considers discrete controls are supported; POV hats are not currently supported as DirectInput does not consider them to be discrete controls.

For bindings with more flexibility provides, you might find the RemoteControls zip useful in combination with a tool like VoiceAttack, or any other tool that supports launching an executable when a button/combo is pressed

![image](https://user-images.githubusercontent.com/360927/179404187-0fc71c70-2e3b-47e6-a057-53bf013559bf.png)

**Comment by fredemmott** [comment]
Will be supported in v1.2 by pretending they're buttons. They will be shown as hats in the UI, but as DirectInput essentially treats hats as axes with a 0->35999 range (and a magic center value), it looks a bit weird in the settings file - for example:

```json
          {
            "Action": "NEXT_PAGE",
            "Buttons": [
              281474976719656
            ]
          }
```

What this means: 281474976719656 is 0x1000000002328

```
0x0001000000002328
  ^^^^ type == hat
0x0001000000002328
      ^^^^ which hat, starting at 0 - so the first hat
0x0001000000002328
          ^^^^ unused
0x0001000000002328
              ^^^^ 0x2328 is 9000, so 90.00 degrees or east
```

So, button 281474976719656  is "First Hat, East"

This scheme doesn't interfere with real buttons, as it leaves space for 2^48 (roughly 281 trillion) buttons per physical device. It supports up to 2^16 (65536) hats per physical device.
