### ISSUE TITLE
Aircraft specific kneeboards don't load when mission with multiple clients loaded in singleplayer

### ISSUE THREAD

**Issue by bbirchnz** [OpenKneeboard/OpenKneeboard#81]
Systems like Liberation that produce multiple client slots and aircraft specific kneeboards won't load the appropriate kneeboard when player choses (or changes) a slot. Cause: onPlayerChangeSlot event doesn't seem to fire, nor does any other obvious gameEvent.

Work around: Run missions like this on a local dedicated server (helps hugely with performance on missions like liberation anyway as offloads most AI work to another core)

Filing a bug on ED Forums.

**Comment by bbirchnz** [comment]
Another possible solution - add callback to OnSimulationFrame and see if its practical to quickly determine own aircraft there.

**Comment by justin-lovell** [comment]
That would be an acceptable solution -- SRS already does a quick poll all  the time, and no one complained about the performance. https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/3afe786669ec827bdd25219ecb2196514fe3039b/Scripts/DCS-SRS/Scripts/DCS-SRSGameGUI.lua#L56-L67

**Comment by fredemmott** [comment]
Putting on to 1.2: unclear about whether this is already fixed or not - will spend some time figuring out how liberation works. Currently I mostly play baltic dragons' campaigns :p

**Comment by fredemmott** [comment]
This will be in v1.2-beta3; I've briefly tested this with liberation.
