### ISSUE TITLE
Add support for duplicating pages/forms/templates

### ISSUE THREAD

**Issue by fredemmott** [OpenKneeboard/OpenKneeboard#82]
For example, 9-line forms. Make it easy to add another page with the same initial content, but no doodles

**Comment by fredemmott** [comment]
If it were a new tab type, these could be done by automatically appending a new page as soon as you start writing on the current one

**Comment by kknuut** [comment]
I have achieved this by creating merged PDF with several copies of same pages. Then have page switch binded to pen tablet buttons. Works great.

I've greated kneeboard in inkscake, export to single page PDF.
Then there are free online tools to merge PDF's  Just drag same single page PDF multiple times and hit merge.
