### ISSUE TITLE
Support folder-of-PDFs-and-images

### ISSUE THREAD

**Issue by fredemmott** [OpenKneeboard/OpenKneeboard#83]
This basically needs a refactoring to separate the 'collection of pages' and 'tab' concept: a PDF *is* a collection of pages, so if a folder tab can contain a PDF and anything else, it contains multiple collections of pages.

**Comment by Ked57** [comment]
Maybe the easier way to do this would be to automaticaly add a tab for each pdf in a folder ? That's how I expected it to work at first

**Comment by drsoran** [comment]
It would be very nice to be able to save multiple kneeboard layouts for different DCS scenarios/servers. But folder support would also solve this. Would be perfectly OK to create a folder for every kneeboard layout and organize the content in subfolders.
