### ISSUE TITLE
Add ability to rename tabs

### ISSUE THREAD

**Issue by Penecruz** [OpenKneeboard/OpenKneeboard#86]
When importing a tab from PDF for example, it would be great to be able to rename the tab to something other than the file name of the imported document.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/73371761/166564786-f5ed8a9f-3a22-46de-b04e-a51db40ac6ec.png">

I think maybe in this Tab settings page a simple rename option via select and type over or right click rename would help.

**Comment by fredemmott** [comment]
Going to add a button:
- initially went for select-and-type-over, but this doesn't play nicely with drag-and-drop reordering
- button is more discoverable than right click
