### ISSUE TITLE
Add Window Capture tab type

### ISSUE THREAD

**Issue by fredemmott** [OpenKneeboard/OpenKneeboard#94]
This should probably be via https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture?view=winrt-22000

Not aiming for general-purpose 'put any window anywhere in VR' (i.e. not aiming to replace OVR Toolkit or built-in steamvr/oculus features), just 'embed a window in a kneeboard tab', keeping the flight-sim focus.

---

Current state:

- [x] capture window
- [x] handle window close
- [x] handle window resize
- [x] handle window (re-)opening after startup
- [x] capture UWP apps, e.g. the windows 10 calculator
- [x] cursor input
- [x] cursor input in 32-bit aps, e.g. discord
- [ ] #224
- [x] settings

**Comment by NoSie** [comment]
Any progress on this feature? For me it's the last missing link for perfect OpenXR FlightSim experience. Having e.g. the Discord window on a page on the Kneeboard would be very uselful and not break immersion (like floating windows).

**Comment by fredemmott** [comment]
Not yet; any progress will automatically show up here.

**Comment by fredemmott** [comment]
Nothing usable yet; so far just bridging between 4 different generations of MS technologies to get from "here's a window ID" to "here's something I can start trying to capture"

**Comment by fredemmott** [comment]
Hmm, input is pretty horrible. Might leave for a later version.

The most straightforward way would:

- only work with Wacom tablets, not mice or Huion tablets (unless Huion fix their implementation of WTOverlap()), and:
- automatically alt-tab to the target window when the pen is near the tablet
- move the system mouse cursor
- automatically alt-tab back to the game when the pen moves away from the tablet

That's pretty clunky. A nicer way - but much more complicated way - would be to rewrite the captured application's input handling automatically.

**Comment by fredemmott** [comment]
![image](https://user-images.githubusercontent.com/360927/208014756-f0727f8b-d09d-4787-9b85-717b360dceaf.png)

**Comment by fredemmott** [comment]
Calling this done.

For now, I'm not supporting UWP input - follow ups for that will be in #224 

Given the length, **please do not report bugs or ask for features by replying to this issue** - instead, open a new issue.
